export interface GreyImage { width: number; height: number; data: Float64Array }
export declare function image(width: number, height: number, data?: Float64Array | null): GreyImage;
export declare const TEST_IMAGES: Readonly<Record<string, string>>;
export declare function testImage(name?: string, size?: number): GreyImage;
export declare function histogram(img: GreyImage, bins?: number): number[];
export declare function negative(img: GreyImage): GreyImage;
export declare function gamma(img: GreyImage, g: number): GreyImage;
export declare function logTransform(img: GreyImage): GreyImage;
export declare function contrastStretch(img: GreyImage, lowPercent?: number, highPercent?: number): { image: GreyImage; low: number; high: number };
export declare function equalize(img: GreyImage): { image: GreyImage; mapping: number[] };
export declare function threshold(img: GreyImage, t: number): GreyImage;
export declare function otsu(img: GreyImage): { threshold: number; variance: number[] };
export declare function bitPlane(img: GreyImage, bit: number): GreyImage;
export declare function correlate(img: GreyImage, kernel: number[][]): GreyImage;
export declare const KERNELS: Readonly<Record<string, { label: string; kernel: number[][] }>>;
export declare function gaussianKernel(sigma: number, radius?: number): number[][];
export declare function medianFilter(img: GreyImage, size?: number): GreyImage;
export declare function addNoise(img: GreyImage, options?: { kind?: 'gaussian' | 'salt-pepper'; amount?: number; seed?: number }): GreyImage;
export declare function gradient(img: GreyImage, operator?: 'sobel' | 'prewitt'): { gx: GreyImage; gy: GreyImage; magnitude: GreyImage; angle: Float64Array };
export declare function canny(img: GreyImage, options?: { sigma?: number; low?: number; high?: number }): { smooth: GreyImage; magnitude: GreyImage; suppressed: GreyImage; edges: GreyImage; edgePixels: number };
export declare function structuringElement(shape?: 'square' | 'cross' | 'disk', size?: number): boolean[][];
export declare function morphology(img: GreyImage, operation: string, element: boolean[][]): GreyImage;
export declare function components(img: GreyImage, connectivity?: 4 | 8): { labels: Int32Array; regions: { label: number; area: number; cx: number; cy: number }[]; count: number };
export declare function fft2(img: GreyImage, inverse?: boolean, imagPart?: ArrayLike<number> | null): { width: number; height: number; re: Float64Array; im: Float64Array };
export declare function spectrumImage(spectrum: { width: number; height: number; re: ArrayLike<number>; im: ArrayLike<number> }): GreyImage;
export declare const FREQUENCY_FILTERS: Readonly<Record<string, string>>;
export declare function frequencyFilter(img: GreyImage, options?: { kind?: string; pass?: 'low' | 'high'; cutoff?: number; order?: number }): { image: GreyImage; spectrum: GreyImage; filtered: GreyImage; response: GreyImage; energyKept: number };
export declare function mse(a: GreyImage, b: GreyImage): number;
export declare function psnr(a: GreyImage, b: GreyImage): number;
export declare function dct8(block: number[][], inverse?: boolean): number[][];
export declare const JPEG_LUMINANCE: readonly (readonly number[])[];
export declare function jpegCompress(img: GreyImage, quality?: number): { image: GreyImage; table: number[][]; nonzeroFraction: number; psnr: number; firstBlock: { pixels: number[][]; coefficients: number[][]; quantised: number[][]; restored: number[][] } | null };
export declare function fromRgba(rgba: ArrayLike<number>, width: number, height: number, size?: number): GreyImage;
