[package]
name = "openentc-studio"
version = "0.1.0"
description = "OpenENTC Studio secure desktop shell"
authors = ["OpenENTC contributors"]
edition = "2021"

[lib]
name = "openentc_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
serde_json = "1"
tauri-plugin-dialog = "2"
serialport = { version = "4.10.1", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
