export declare function fft(re: number[], im: number[], inverse?: boolean): void;
export declare function powerSpectrum(frame: number[], nfft?: number): number[];
export declare function hamming(n: number): number[];
export declare function synthesizeVowel(options?: { f0?: number; formants?: number[][]; fs?: number; duration?: number; noise?: number; seed?: number }): number[];
export declare function synthesizeNoise(options?: { fs?: number; duration?: number; seed?: number }): number[];
export declare function frames(signal: number[], length: number, step: number): number[][];
export declare function shortTimeFeatures(signal: number[], options?: { fs?: number; frameMs?: number; stepMs?: number }): { times: number[]; energy: number[]; zcr: number[]; label: ('voiced' | 'unvoiced' | 'silence')[]; length: number; step: number };
export declare function pitchAutocorrelation(frame: number[], options?: { fs?: number; fMin?: number; fMax?: number; clip?: number }): { f0: number; lag: number; strength: number; autocorrelation: number[] };
export declare function pitchAmdf(frame: number[], options?: { fs?: number; fMin?: number; fMax?: number }): { f0: number; lag: number; amdf: number[] };
export declare function cepstrum(frame: number[], options?: { fs?: number; fMin?: number; fMax?: number; nfft?: number | null; lifter?: number }): { cepstrum: number[]; f0: number; quefrency: number; logSpectrum: number[]; envelope: number[]; nfft: number };
export declare function autocorrelation(x: number[], p: number): number[];
export declare function levinson(r: number[], p: number): { a: number[]; reflection: number[]; error: number };
export declare function lpc(frame: number[], order?: number, options?: { preemphasis?: number }): { a: number[]; reflection: number[]; error: number; r: number[]; gain: number };
export declare function lpcSpectrum(a: number[], gain: number, options?: { fs?: number; points?: number }): { freqs: number[]; db: number[] };
export declare function polynomialRoots(coefficients: number[], options?: { iterations?: number; tolerance?: number }): { re: number; im: number }[];
export declare function formants(a: number[], options?: { fs?: number; maxBandwidth?: number; minFrequency?: number }): { frequency: number; bandwidth: number }[];
export declare function spectrogram(signal: number[], options?: { fs?: number; frameMs?: number; stepMs?: number; nfft?: number }): { db: number[][]; times: number[]; freqs: number[] };
export declare function hzToMel(hz: number): number;
export declare function melToHz(mel: number): number;
export declare function melFilterbank(options?: { filters?: number; nfft?: number; fs?: number; lowFreq?: number; highFreq?: number | null }): number[][];
export declare function mfcc(signal: number[], options?: { fs?: number; winlen?: number; winstep?: number; numcep?: number; nfilt?: number; nfft?: number; lowFreq?: number; highFreq?: number | null; preemph?: number; ceplifter?: number; appendEnergy?: boolean }): number[][];
