// Learning Hub courseware: six ENTC tracks of short lessons. Each lesson explains one idea in
// plain English, lists the key formulas, links to the lab where it can be tried, and ends with
// a quiz (multiple choice plus numeric questions with fresh numbers on every attempt). Every
// track also has a viva-voce question bank.

const mcq = (id, prompt, options, answer, explain) => ({ type: 'mcq', id, prompt, options, answer, explain });
const num = (id, params, prompt, answer, unit, explain, tolerance = 0.02) => ({ type: 'numeric', id, params, prompt, answer, unit, explain, tolerance });
const E = (value, unit = '') => { const p = [[1e9, 'G'], [1e6, 'M'], [1e3, 'k'], [1, ''], [1e-3, 'm'], [1e-6, 'µ'], [1e-9, 'n'], [1e-12, 'p']]; const [s, x] = p.find(([v]) => Math.abs(value) >= v * 0.9999) ?? p.at(-1); return `${Number((value / s).toPrecision(4))} ${x}${unit}`; };

export const TRACKS = [
  {
    id: 'circuits', title: 'Circuit foundations', level: 'Beginner', color: '#60a5fa',
    lessons: [
      { id: 'ohm-kirchhoff', title: "Ohm's law and Kirchhoff's laws", minutes: 10, lab: { module: 'theory', label: 'Network Theory' },
        summary: ['Every circuit calculation starts with three rules. Ohm\'s law says the voltage across a resistor is the current through it times its resistance. Kirchhoff\'s current law (KCL) says the currents entering a node add up to the currents leaving it — charge is not stored in a wire. Kirchhoff\'s voltage law (KVL) says the voltages around any closed loop add up to zero — energy is conserved.', 'Resistors in series add; resistors in parallel combine as the reciprocal of the sum of reciprocals. Two resistors in parallel give R1·R2/(R1 + R2), which is always smaller than the smaller one.'],
        formulas: ['V = I·R', 'ΣI(in) = ΣI(out)  (KCL)', 'ΣV around a loop = 0  (KVL)', 'Series: R = R1 + R2', 'Parallel: R = R1·R2 / (R1 + R2)'],
        questions: [
          num('ohm', { v: [5, 24, 1], r: [100, 4700, 100] }, (p) => `A ${p.v} V supply drives a ${E(p.r, 'Ω')} resistor. What current flows?`, (p) => p.v / p.r, 'A', (p, a) => `I = V/R = ${p.v}/${p.r} = ${E(a, 'A')}.`),
          num('parallel', { a: [1000, 10000, 100], b: [1000, 10000, 100] }, (p) => `What is ${E(p.a, 'Ω')} in parallel with ${E(p.b, 'Ω')}?`, (p) => p.a * p.b / (p.a + p.b), 'Ω', (p, a) => `R = R1·R2/(R1 + R2) = ${E(a, 'Ω')}.`),
          mcq('kcl', 'Which law follows from conservation of charge?', ['KVL', 'KCL', 'Ohm\'s law', 'Faraday\'s law'], 1, 'KCL: charge cannot pile up at a node, so currents in equal currents out.'),
        ] },
      { id: 'divider', title: 'Voltage and current dividers', minutes: 8, lab: { module: 'circuit', label: 'Circuit Lab' },
        summary: ['Two resistors in series across a source share the voltage in proportion to their resistance: the output across R2 is Vin·R2/(R1 + R2). This is how sensors, potentiometers and bias networks produce a fraction of a voltage.', 'A load connected across R2 is in parallel with it, so the output drops. Keep the load at least ten times larger than R2, or buffer the divider with an op-amp follower.'],
        formulas: ['Vout = Vin·R2 / (R1 + R2)', 'I2 = I·R1 / (R1 + R2)  (current divider)'],
        questions: [
          num('vdiv', { vin: [5, 24, 1], r1: [1000, 10000, 1000], r2: [1000, 10000, 1000] }, (p) => `Vin = ${p.vin} V, R1 = ${E(p.r1, 'Ω')} (top), R2 = ${E(p.r2, 'Ω')} (bottom). Find Vout across R2.`, (p) => p.vin * p.r2 / (p.r1 + p.r2), 'V', (p, a) => `Vout = ${p.vin}·${p.r2}/(${p.r1} + ${p.r2}) = ${E(a, 'V')}.`),
          num('loaded', { r: [1000, 10000, 1000], load: { choices: [1000, 2000, 5000, 10000] } }, (p) => `A 10 V source feeds two equal ${E(p.r, 'Ω')} resistors. A ${E(p.load, 'Ω')} load is connected across the bottom one. What is the output voltage now?`, (p) => { const rp = p.r * p.load / (p.r + p.load); return 10 * rp / (p.r + rp); }, 'V', (p, a) => `The bottom resistor and load in parallel make ${E(p.r * p.load / (p.r + p.load), 'Ω')}, so Vout = ${E(a, 'V')} instead of 5 V.`),
          mcq('buffer', 'How do you stop a load from pulling down a divider output?', ['Use larger R1', 'Add a voltage follower (op-amp buffer)', 'Add a series capacitor', 'Reverse the supply'], 1, 'A follower has very high input resistance and low output resistance.'),
        ] },
      { id: 'thevenin', title: 'Thévenin and Norton equivalents', minutes: 12, lab: { module: 'theory', label: 'Network Theory → Thévenin' },
        summary: ['Any linear circuit seen from two terminals behaves like one voltage source Vth in series with one resistance Rth (Thévenin), or one current source In in parallel with Rth (Norton). Vth is the open-circuit voltage, In is the short-circuit current, and Rth = Vth/In — or the resistance seen with all independent sources turned off.', 'Maximum power reaches a load when RL = Rth; the efficiency is then only 50 %.'],
        formulas: ['Vth = Voc', 'In = Isc', 'Rth = Voc / Isc', 'Pmax = Vth² / (4·Rth)  at RL = Rth'],
        questions: [
          num('pmax', { vth: [5, 20, 1], rth: [10, 100, 5] }, (p) => `A source has Vth = ${p.vth} V and Rth = ${p.rth} Ω. What is the maximum power it can deliver to a load?`, (p) => p.vth ** 2 / (4 * p.rth), 'W', (p, a) => `Pmax = Vth²/(4Rth) = ${E(a, 'W')} at RL = ${p.rth} Ω.`),
          num('rth', { voc: [6, 24, 1], isc: [0.05, 2, 0.05] }, (p) => `The open-circuit voltage is ${p.voc} V and the short-circuit current is ${E(p.isc, 'A')}. Find Rth.`, (p) => p.voc / p.isc, 'Ω', (p, a) => `Rth = Voc/Isc = ${E(a, 'Ω')}.`),
          mcq('rth-sources', 'To find Rth directly, independent voltage sources are…', ['opened', 'shorted', 'doubled', 'left unchanged'], 1, 'Turning a voltage source off means 0 V: replace it with a short (current sources become open circuits).'),
        ] },
      { id: 'rc-transient', title: 'RC and RL transients', minutes: 12, lab: { module: 'circuit', label: 'Circuit Lab → transient' },
        summary: ['A capacitor charging through a resistor does not jump to the final voltage. It follows an exponential with time constant τ = RC: after one τ it reaches 63 %, and after 5τ it is practically finished. An inductor with a resistor behaves the same way with τ = L/R.', 'The general first-order response is v(t) = v(∞) + [v(0) − v(∞)]·e^(−t/τ).'],
        formulas: ['τ = R·C,  τ = L/R', 'v(t) = V·(1 − e^(−t/τ))  (charging)', 'v(t) = v(∞) + [v(0) − v(∞)]·e^(−t/τ)'],
        questions: [
          num('tau', { r: [1000, 100000, 1000], c: { choices: [1e-9, 10e-9, 100e-9, 1e-6, 10e-6] } }, (p) => `R = ${E(p.r, 'Ω')}, C = ${E(p.c, 'F')}. What is the time constant?`, (p) => p.r * p.c, 's', (p, a) => `τ = RC = ${E(a, 's')}.`),
          num('charge', { v: [5, 15, 1], n: { choices: [1, 2, 3] } }, (p) => `A capacitor charges from 0 towards ${p.v} V. What is its voltage after ${p.n} time constant(s)?`, (p) => p.v * (1 - Math.exp(-p.n)), 'V', (p, a) => `v = V(1 − e^−${p.n}) = ${E(a, 'V')}.`),
          mcq('five-tau', 'After about how many time constants is a first-order circuit considered settled?', ['1', '2', '5', '20'], 2, 'After 5τ the remaining error is e^−5 ≈ 0.7 %.'),
        ] },
      { id: 'phasors', title: 'AC, phasors and impedance', minutes: 14, lab: { module: 'console', label: 'Math Console (phasors example)' },
        summary: ['A sinusoid at one frequency is fully described by its amplitude and phase, so we write it as a complex number called a phasor. Resistors, inductors and capacitors then become impedances: R, jωL and 1/(jωC). Ohm\'s and Kirchhoff\'s laws work unchanged with complex numbers.', 'Inductive reactance grows with frequency, capacitive reactance falls. At resonance in a series RLC circuit they cancel, the impedance is just R and the current peaks at f0 = 1/(2π√(LC)).'],
        formulas: ['Z_R = R,  Z_L = jωL,  Z_C = 1/(jωC),  ω = 2πf', '|Z| = √(R² + X²),  φ = atan(X/R)', 'f0 = 1 / (2π√(LC))', 'Q = (1/R)·√(L/C)  (series RLC)'],
        questions: [
          num('xc', { f: [50, 5000, 50], c: { choices: [100e-9, 1e-6, 10e-6] } }, (p) => `Find the reactance of a ${E(p.c, 'F')} capacitor at ${p.f} Hz.`, (p) => 1 / (2 * Math.PI * p.f * p.c), 'Ω', (p, a) => `Xc = 1/(2πfC) = ${E(a, 'Ω')}.`),
          num('f0', { l: { choices: [1e-3, 10e-3, 100e-3] }, c: { choices: [10e-9, 100e-9, 1e-6] } }, (p) => `L = ${E(p.l, 'H')}, C = ${E(p.c, 'F')}. Find the resonant frequency.`, (p) => 1 / (2 * Math.PI * Math.sqrt(p.l * p.c)), 'Hz', (p, a) => `f0 = 1/(2π√(LC)) = ${E(a, 'Hz')}.`),
          mcq('phase-l', 'In a pure inductor the current…', ['leads the voltage by 90°', 'lags the voltage by 90°', 'is in phase', 'is zero'], 1, 'V = jωL·I, so the voltage leads and the current lags by 90° ("ELI").'),
        ] },
      { id: 'diodes-opamps', title: 'Diodes, rectifiers and op-amps', minutes: 14, lab: { module: 'circuit', label: 'Circuit Lab (examples)' },
        summary: ['A silicon diode conducts in one direction once about 0.7 V is across it. A bridge rectifier uses four diodes so both half-cycles charge the smoothing capacitor; the ripple is roughly I/(2fC).', 'An ideal op-amp with negative feedback keeps its two inputs at the same voltage and draws no input current. That gives an inverting gain of −Rf/Rin and a non-inverting gain of 1 + Rf/Rg.'],
        formulas: ['Peak output of a bridge ≈ Vpeak − 1.4 V', 'Ripple ≈ I / (2·f·C)  (full wave)', 'Inverting: Av = −Rf/Rin', 'Non-inverting: Av = 1 + Rf/Rg'],
        questions: [
          num('inv-gain', { rf: [10000, 100000, 10000], rin: [1000, 10000, 1000], vin: [0.1, 1, 0.1] }, (p) => `An inverting amplifier has Rf = ${E(p.rf, 'Ω')}, Rin = ${E(p.rin, 'Ω')} and Vin = ${p.vin} V. Find Vout.`, (p) => -p.rf / p.rin * p.vin, 'V', (p, a) => `Vout = −(Rf/Rin)·Vin = ${E(a, 'V')}.`),
          num('ripple', { i: [0.1, 1, 0.1], c: { choices: [470e-6, 1000e-6, 2200e-6, 4700e-6] } }, (p) => `A 50 Hz full-wave rectifier supplies ${p.i} A from a ${E(p.c, 'F')} capacitor. Estimate the peak-to-peak ripple.`, (p) => p.i / (2 * 50 * p.c), 'V', (p, a) => `ΔV ≈ I/(2fC) = ${E(a, 'V')}.`),
          mcq('virtual-short', 'With negative feedback, an ideal op-amp makes…', ['V+ = V− (virtual short)', 'the output always 0 V', 'the input current large', 'the gain infinite at the output'], 0, 'High open-loop gain plus feedback forces the input difference towards zero.'),
        ] },
    ],
    viva: [
      ['State Thévenin\'s theorem.', 'Any linear two-terminal network can be replaced by a voltage source equal to its open-circuit voltage in series with the resistance seen at the terminals with independent sources turned off.'],
      ['What is the superposition theorem and where does it fail?', 'In a linear circuit the response to several sources is the sum of the responses to each source alone. It does not apply to power (which is not linear) or to non-linear elements such as diodes.'],
      ['Why does a capacitor block DC?', 'Its reactance 1/(2πfC) is infinite at f = 0: once charged no steady current flows.'],
      ['What is the quality factor of a resonant circuit?', 'Q = f0/bandwidth — the ratio of energy stored to energy lost per cycle; a higher Q means a sharper resonance.'],
      ['Why is the efficiency only 50 % at maximum power transfer?', 'With RL = Rth the same current flows through both, so equal power is dissipated in the source resistance and in the load.'],
      ['What is the difference between a bridge and a centre-tap rectifier?', 'A bridge uses four diodes and the whole secondary winding, with two diode drops; a centre-tap uses two diodes and needs a centre-tapped transformer, with one drop and twice the diode reverse voltage.'],
      ['What is a virtual ground?', 'In an inverting op-amp with the + input grounded, negative feedback holds the − input at 0 V without connecting it to ground.'],
      ['What are the units of time constant RC?', 'Seconds: ohms × farads = (V/A)·(A·s/V) = s.'],
    ],
  },
  {
    id: 'digital', title: 'Digital systems', level: 'Beginner', color: '#e879f9',
    lessons: [
      { id: 'numbers', title: 'Number systems and codes', minutes: 10, lab: { module: 'logic', label: 'Digital Logic Lab → codes' },
        summary: ['Digital circuits store numbers in binary. Each extra bit doubles the range: n bits count from 0 to 2ⁿ − 1. Hexadecimal groups four bits per digit and octal three bits, which makes long binary numbers readable.', 'Negative numbers use two\'s complement: invert all bits and add one. An n-bit two\'s complement number covers −2ⁿ⁻¹ … 2ⁿ⁻¹ − 1, and addition works the same as for unsigned numbers. Gray code changes only one bit between neighbours, which avoids glitches in encoders.'],
        formulas: ['Range of n unsigned bits: 0 … 2ⁿ − 1', 'Two\'s complement range: −2ⁿ⁻¹ … 2ⁿ⁻¹ − 1', '−x = (NOT x) + 1', 'Gray: g = b XOR (b >> 1)'],
        questions: [
          num('binary', { n: [5, 250, 1] }, (p) => `How many 1s are in the binary form of ${p.n}?`, (p) => p.n.toString(2).split('').filter((c) => c === '1').length, '', (p) => `${p.n} = ${p.n.toString(2)}₂.`, 0),
          num('twos', { bits: { choices: [4, 8, 12, 16] } }, (p) => `What is the most negative number in ${p.bits}-bit two's complement?`, (p) => -(2 ** (p.bits - 1)), '', (p, a) => `−2^(n−1) = ${a}.`, 0),
          mcq('gray', 'Why is Gray code used in rotary encoders?', ['It needs fewer bits', 'Only one bit changes between adjacent values', 'It is easier to add', 'It detects all errors'], 1, 'If two bits changed at slightly different moments, a wrong intermediate code could be read.'),
        ] },
      { id: 'boolean', title: 'Boolean algebra and K-maps', minutes: 14, lab: { module: 'logic', label: 'Digital Logic Lab → K-map' },
        summary: ['Boolean algebra simplifies logic so circuits need fewer gates. De Morgan\'s laws turn ANDs into ORs: (A·B)′ = A′ + B′ and (A + B)′ = A′·B′. NAND and NOR are universal — any function can be built from either alone.', 'A Karnaugh map arranges the truth table in Gray-code order so adjacent cells differ by one variable. Grouping 1s in rectangles of 1, 2, 4, 8 … cells removes the variables that change inside the group. Don\'t-care cells can be included when they make a group larger.'],
        formulas: ['(A·B)′ = A′ + B′,  (A + B)′ = A′·B′', 'A + A·B = A  (absorption)', 'A + A′·B = A + B', 'An n-variable K-map has 2ⁿ cells'],
        questions: [
          mcq('demorgan', '(A + B)′ equals', ['A′ + B′', 'A′·B′', 'A·B', 'A′ + B'], 1, 'De Morgan: invert each variable and swap OR for AND.'),
          num('minterms', { n: [2, 6, 1] }, (p) => `How many cells does a ${p.n}-variable K-map have?`, (p) => 2 ** p.n, '', (p, a) => `2^${p.n} = ${a}.`, 0),
          mcq('universal', 'Which single gate type can build any logic function?', ['XOR', 'NAND', 'AND', 'NOT'], 1, 'NAND (and NOR) are universal; AND or XOR alone are not.'),
        ] },
      { id: 'combinational', title: 'Combinational circuits', minutes: 12, lab: { module: 'logic', label: 'Digital Logic Lab → gate simulator' },
        summary: ['A combinational circuit\'s output depends only on its present inputs. Half adders give sum A ⊕ B and carry A·B; a full adder adds a carry-in too. A 2ⁿ-to-1 multiplexer selects one of 2ⁿ inputs with n select lines; a decoder turns an n-bit code into one of 2ⁿ outputs.', 'Ripple-carry adders are simple but slow because each carry waits for the previous one; carry-look-ahead adders compute carries in parallel.'],
        formulas: ['Half adder: S = A ⊕ B, C = A·B', 'Full adder: S = A ⊕ B ⊕ Cin, Cout = A·B + Cin·(A ⊕ B)', 'A 2ⁿ:1 mux needs n select lines'],
        questions: [
          num('mux', { inputs: { choices: [4, 8, 16, 32, 64] } }, (p) => `How many select lines does a ${p.inputs}-to-1 multiplexer need?`, (p) => Math.log2(p.inputs), '', (p, a) => `log2(${p.inputs}) = ${a}.`, 0),
          mcq('fa-sum', 'The sum output of a full adder is', ['A·B·Cin', 'A ⊕ B ⊕ Cin', 'A + B + Cin', '(A ⊕ B)·Cin'], 1, 'The sum is 1 when an odd number of inputs are 1.'),
          num('ripple', { bits: { choices: [4, 8, 16, 32] }, delay: [2, 10, 1] }, (p) => `Each full adder adds ${p.delay} ns of carry delay. What is the worst-case carry delay of a ${p.bits}-bit ripple-carry adder?`, (p) => p.bits * p.delay * 1e-9, 's', (p, a) => `n·tcarry = ${E(a, 's')}.`),
        ] },
      { id: 'sequential', title: 'Flip-flops and counters', minutes: 14, lab: { module: 'logic', label: 'Digital Logic Lab → flip-flops' },
        summary: ['Sequential circuits remember. A D flip-flop copies D to Q on the clock edge; a JK flip-flop toggles when J = K = 1; a T flip-flop toggles when T = 1. Setup and hold times must be met around the clock edge, or the output can go metastable.', 'A ripple counter chains toggle flip-flops: each stage divides the frequency by two, so an n-bit counter divides by 2ⁿ. A synchronous counter clocks all stages together and has no ripple delay.'],
        formulas: ['D: Q⁺ = D', 'JK: Q⁺ = J·Q′ + K′·Q', 'T: Q⁺ = T ⊕ Q', 'Mod-N counter needs ⌈log2 N⌉ flip-flops'],
        questions: [
          num('divider', { bits: [2, 10, 1], f: { choices: [1e6, 10e6, 32768, 50e6] } }, (p) => `A ${p.bits}-bit binary ripple counter is clocked at ${E(p.f, 'Hz')}. What frequency comes out of the last stage?`, (p) => p.f / 2 ** p.bits, 'Hz', (p, a) => `f/2^${p.bits} = ${E(a, 'Hz')}.`),
          num('modn', { n: [3, 200, 1] }, (p) => `How many flip-flops does a mod-${p.n} counter need?`, (p) => Math.ceil(Math.log2(p.n)), '', (p, a) => `⌈log2 ${p.n}⌉ = ${a}.`, 0),
          mcq('jk', 'A JK flip-flop with J = K = 1 will', ['reset', 'set', 'toggle', 'hold'], 2, 'Q⁺ = J·Q′ + K′·Q = Q′.'),
        ] },
      { id: 'verilog', title: 'Describing hardware in Verilog', minutes: 15, lab: { module: 'fpga', label: 'FPGA & Digital → Verilog simulator' },
        summary: ['Verilog describes hardware, not a sequence of steps. A continuous assignment (assign y = a & b;) is a wire that always follows its inputs. An always @(posedge clk) block describes flip-flops; use non-blocking assignments (<=) inside it so all registers update together.', 'A testbench is Verilog that drives inputs and checks outputs. $display and $monitor print values, #10 waits 10 time units, and $dumpvars records a VCD waveform.'],
        formulas: ['assign y = a & b;  // combinational', 'always @(posedge clk) q <= d;  // flip-flop', 'Blocking (=) for combinational always blocks, non-blocking (<=) for clocked ones'],
        questions: [
          mcq('nonblocking', 'Inside always @(posedge clk), which assignment should you use for registers?', ['=', '<=', 'assign', '=='], 1, 'Non-blocking assignments sample all right-hand sides first, modelling flip-flops correctly.'),
          mcq('assign', 'assign y = a ^ b; describes', ['a flip-flop', 'a latch', 'an XOR gate (combinational)', 'a clock'], 2, 'Continuous assignments model combinational logic.'),
          num('clock', { half: [1, 50, 1] }, (p) => `A testbench toggles clk every #${p.half} time units (ns). What is the clock frequency?`, (p) => 1 / (2 * p.half * 1e-9), 'Hz', (p, a) => `Period = 2 × ${p.half} ns, so f = ${E(a, 'Hz')}.`),
        ] },
      { id: 'cmos', title: 'CMOS logic and power', minutes: 12, lab: { module: 'vlsi', label: 'VLSI Lab' },
        summary: ['A CMOS inverter is a PMOS pull-up and an NMOS pull-down. In either steady state one transistor is off, so almost no static current flows — the reason CMOS dominates. Power is spent mainly when nodes switch: P = α·C·V²·f.', 'Noise margins measure how much noise an input can take: NMH = VOH − VIH and NML = VIL − VOL. Making the PMOS wider (about two to three times the NMOS) balances the rise and fall times because holes are slower than electrons.'],
        formulas: ['P_dynamic = α·C·VDD²·f', 'NMH = VOH − VIH,  NML = VIL − VOL', 'tp ≈ (tpHL + tpLH) / 2'],
        questions: [
          num('dynpower', { c: { choices: [1e-12, 10e-12, 50e-12] }, v: { choices: [1.2, 1.8, 3.3, 5] }, f: { choices: [10e6, 100e6, 1e9] } }, (p) => `A node of ${E(p.c, 'F')} switches every cycle (α = 1) at ${E(p.f, 'Hz')} with VDD = ${p.v} V. Find the dynamic power.`, (p) => p.c * p.v ** 2 * p.f, 'W', (p, a) => `P = C·V²·f = ${E(a, 'W')}.`),
          mcq('static', 'Why does a CMOS gate draw almost no static current?', ['The supply is low', 'One of the two transistors is always off in a steady state', 'The transistors are small', 'The gate is clocked'], 1, 'There is no DC path from VDD to ground except during switching (and leakage).'),
          mcq('pmos-width', 'Why is the PMOS usually made wider than the NMOS?', ['To save area', 'Hole mobility is lower than electron mobility', 'To raise the threshold', 'To reduce capacitance'], 1, 'A wider PMOS gives the same current drive, balancing rise and fall times.'),
        ] },
    ],
    viva: [
      ['What is the difference between a latch and a flip-flop?', 'A latch is level-sensitive (transparent while enabled); a flip-flop is edge-triggered and changes only at the clock edge.'],
      ['What is a race-around condition?', 'In a level-triggered JK flip-flop with J = K = 1, the output toggles repeatedly while the clock is high. Edge triggering or master-slave design removes it.'],
      ['Why are NAND and NOR called universal gates?', 'Every Boolean function — NOT, AND and OR included — can be built from NAND gates alone (or NOR alone).'],
      ['What is metastability?', 'If the data changes inside the setup/hold window, a flip-flop can hover between 0 and 1 for an unpredictable time before settling. Synchronisers with two flip-flops reduce the risk.'],
      ['What is fan-out?', 'The number of gate inputs one output can drive while staying within its voltage and timing specifications.'],
      ['Synchronous vs asynchronous counter?', 'All flip-flops of a synchronous counter share the clock and change together; in an asynchronous (ripple) counter each stage clocks the next, so delays add up.'],
      ['Blocking vs non-blocking assignment in Verilog?', 'Blocking (=) executes in order like software; non-blocking (<=) evaluates all right-hand sides first and updates together at the end of the time step — the behaviour of flip-flops.'],
      ['What are noise margins?', 'The amount of noise a logic input can tolerate: NMH = VOH − VIH and NML = VIL − VOL.'],
    ],
  },
  {
    id: 'embedded', title: 'Embedded C and MCUs', level: 'Intermediate', color: '#fbbf24',
    lessons: [
      { id: '8051', title: '8051 architecture and timers', minutes: 15, lab: { module: 'mcu', label: 'Microcontroller Lab → 8051' },
        summary: ['The 8051 has 4 KB of on-chip ROM, 128 bytes of RAM, four 8-bit ports, two 16-bit timers and a serial port. With a 12 MHz crystal one machine cycle takes 12 clock periods = 1 µs.', 'In mode 1 a timer counts 16 bits from its start value up to FFFFh and sets TFx on overflow. To get a delay of N machine cycles, load 65536 − N. Mode 2 is 8-bit auto-reload, used for baud rates.'],
        formulas: ['Machine cycle = 12 / f_osc', 'Mode 1 reload = 65536 − N', 'Mode 2 baud (SMOD = 0) = f_osc / (12·32·(256 − TH1))'],
        questions: [
          num('mc', { f: { choices: [6e6, 11.0592e6, 12e6, 24e6] } }, (p) => `What is the 8051 machine-cycle time with a ${E(p.f, 'Hz')} crystal?`, (p) => 12 / p.f, 's', (p, a) => `12/f = ${E(a, 's')}.`),
          num('reload', { ms: [1, 50, 1] }, (p) => `With a 12 MHz crystal, what decimal value goes into TH0:TL0 (mode 1) for a ${p.ms} ms delay?`, (p) => 65536 - p.ms * 1000, '', (p, a) => `N = ${p.ms * 1000} machine cycles, reload = 65536 − N = ${a}.`, 0),
          num('baud', { th1: { choices: [0xfd, 0xfa, 0xf4, 0xe8] } }, (p) => `With 11.0592 MHz, SMOD = 0 and timer 1 in mode 2 with TH1 = ${p.th1} (${p.th1.toString(16).toUpperCase()}h), what is the baud rate?`, (p) => 11.0592e6 / (12 * 32 * (256 - p.th1)), 'Bd', (p, a) => `11.0592 MHz/(384·${256 - p.th1}) = ${Math.round(a)} Bd.`),
        ] },
      { id: 'gpio-pwm', title: 'Arduino GPIO, PWM and timers', minutes: 12, lab: { module: 'mcu', label: 'Microcontroller Lab → Arduino Uno' },
        summary: ['digitalWrite sets a pin high or low; pinMode chooses input, output or input with pull-up. A button to ground with INPUT_PULLUP reads LOW when pressed.', 'analogWrite produces PWM: the pin switches at a fixed frequency (≈ 490 Hz or 980 Hz on the Uno) and the duty cycle sets the average voltage — duty × 5 V. An RC low-pass filter turns PWM into a real analogue voltage.'],
        formulas: ['V_avg = D · V_high', 'analogWrite(pin, n): D = n / 255', 'Fast PWM frequency = f_clk / (N · 256)'],
        questions: [
          num('pwm', { n: [0, 255, 1] }, (p) => `analogWrite(9, ${p.n}) on a 5 V Arduino. What is the average output voltage?`, (p) => 5 * p.n / 255, 'V', (p, a) => `5 × ${p.n}/255 = ${E(a, 'V')}.`),
          num('fastpwm', { n: { choices: [1, 8, 64, 256] } }, (p) => `Timer0 in fast PWM mode with prescaler ${p.n} on a 16 MHz Uno. What is the PWM frequency?`, (p) => 16e6 / (p.n * 256), 'Hz', (p, a) => `16 MHz/(${p.n}·256) = ${E(a, 'Hz')}.`),
          mcq('pullup', 'With pinMode(2, INPUT_PULLUP) and a button to ground, pressing the button reads', ['HIGH', 'LOW', 'floating', '512'], 1, 'The internal pull-up holds the pin HIGH; the closed button connects it to ground.'),
        ] },
      { id: 'adc', title: 'Reading sensors with the ADC', minutes: 12, lab: { module: 'adc', label: 'ADC & DAC Lab' },
        summary: ['An n-bit ADC divides its reference into 2ⁿ steps. The Uno\'s 10-bit ADC with a 5 V reference gives about 4.9 mV per count, so analogRead returns round(Vin/Vref × 1023) (the datasheet uses 1024).', 'Quantisation adds noise: an ideal n-bit converter has SNR = 6.02n + 1.76 dB. A SAR converter finds the code bit by bit with a DAC and comparator in n steps.'],
        formulas: ['LSB = Vref / 2ⁿ', 'code = floor(Vin / LSB)', 'SNR_ideal = 6.02·n + 1.76 dB'],
        questions: [
          num('lsb', { bits: { choices: [8, 10, 12, 16] }, vref: { choices: [1.1, 2.5, 3.3, 5] } }, (p) => `What is 1 LSB of a ${p.bits}-bit ADC with a ${p.vref} V reference?`, (p) => p.vref / 2 ** p.bits, 'V', (p, a) => `${p.vref}/2^${p.bits} = ${E(a, 'V')}.`),
          num('snr', { bits: [6, 18, 1] }, (p) => `What is the ideal SNR of a ${p.bits}-bit ADC for a full-scale sine wave?`, (p) => 6.02 * p.bits + 1.76, 'dB', (p, a) => `6.02·${p.bits} + 1.76 = ${a.toFixed(2)} dB.`, 0.005),
          num('lm35', { t: [5, 120, 1] }, (p) => `An LM35 gives 10 mV/°C. At ${p.t} °C, what does analogRead return with the 1.1 V internal reference (10-bit, code = Vin·1024/Vref rounded down)?`, (p) => Math.floor(p.t * 0.01 * 1024 / 1.1), '', (p, a) => `${p.t * 10} mV × 1024/1.1 V → ${a}.`, 0.002),
        ] },
      { id: 'serial', title: 'UART, I²C and SPI', minutes: 14, lab: { module: 'mcu', label: 'Microcontroller Lab → logic analyser' },
        summary: ['UART sends a start bit (0), 5–9 data bits LSB first, an optional parity bit and stop bits (1) at an agreed baud rate — no clock wire. I²C uses two open-drain wires (SDA, SCL) and 7-bit addresses so many chips share one bus; every byte is followed by an ACK bit.', 'SPI uses a clock, MOSI, MISO and one chip-select per device. It is full duplex and fast, and the clock polarity and phase (modes 0–3) must match the device.'],
        formulas: ['UART frame bits = 1 start + data + parity + stop', 'Byte time = frame bits / baud', 'I²C address byte = (address << 1) | R/W'],
        questions: [
          num('uart', { baud: { choices: [9600, 19200, 57600, 115200] } }, (p) => `How long does one 8N1 UART character (start + 8 data + 1 stop) take at ${p.baud} baud?`, (p) => 10 / p.baud, 's', (p, a) => `10 bits/${p.baud} = ${E(a, 's')}.`),
          num('i2c', { address: { choices: [0x27, 0x3c, 0x48, 0x50, 0x68] } }, (p) => `A device has 7-bit I²C address 0x${p.address.toString(16)}. What byte (decimal) is sent first to WRITE to it?`, (p) => p.address << 1, '', (p, a) => `(0x${p.address.toString(16)} << 1) | 0 = 0x${a.toString(16)} = ${a}.`, 0),
          mcq('spi-wires', 'Which bus needs a separate select line for each slave?', ['UART', 'I²C', 'SPI', 'CAN'], 2, 'SPI chooses the device with its chip-select (SS) line; I²C uses addresses.'),
        ] },
      { id: 'interrupts', title: 'Interrupts', minutes: 10, lab: { module: 'mcu', label: 'Microcontroller Lab (interrupt example)' },
        summary: ['An interrupt pauses the main program, runs a short service routine (ISR) and returns. It is better than polling when events are rare or must be handled quickly.', 'Keep ISRs short, share variables through volatile globals, and remember that several 8051 interrupts have fixed priorities (INT0, TF0, INT1, TF1, serial) unless IP changes them.'],
        formulas: ['Latency = time to finish the current instruction + stacking + jump', '8051 vector address = 0003h + 8·n'],
        questions: [
          mcq('volatile', 'Why should a variable changed inside an ISR be declared volatile?', ['To save RAM', 'So the compiler always re-reads it instead of keeping a cached copy', 'To make it faster', 'To put it in ROM'], 1, 'Without volatile the main loop may never see the ISR\'s update.'),
          num('vector', { n: [0, 4, 1] }, (p) => `The 8051 interrupt vectors are at 0003h + 8·n. What is the vector address (decimal) for n = ${p.n}?`, (p) => 3 + 8 * p.n, '', (p, a) => `0003h + ${8 * p.n} = ${a} (= ${a.toString(16).toUpperCase()}h).`, 0),
          mcq('polling', 'When is polling acceptable instead of interrupts?', ['Never', 'When events are frequent and timing is relaxed', 'Only for UART', 'Only on 32-bit MCUs'], 1, 'Polling is simple when the CPU has nothing else to do or the event is predictable.'),
        ] },
      { id: 'rtos', title: 'Real-time scheduling', minutes: 14, lab: { module: 'rtos', label: 'RTOS Scheduler' },
        summary: ['A real-time system must finish tasks before their deadlines. Rate-monotonic scheduling gives higher priority to tasks with shorter periods; it is guaranteed to work if utilisation U = Σ Ci/Ti ≤ n(2^(1/n) − 1) (69 % for many tasks). Earliest-deadline-first works up to U = 100 %.', 'Priority inversion happens when a low-priority task holds a lock needed by a high-priority task while a medium task runs; priority inheritance fixes it.'],
        formulas: ['U = Σ Ci / Ti', 'RM bound: U ≤ n(2^(1/n) − 1)', 'EDF: U ≤ 1'],
        questions: [
          num('util', { c1: [1, 3, 1], t1: [5, 10, 1], c2: [1, 4, 1], t2: [10, 20, 2] }, (p) => `Task 1: C = ${p.c1} ms, T = ${p.t1} ms. Task 2: C = ${p.c2} ms, T = ${p.t2} ms. What is the total utilisation?`, (p) => p.c1 / p.t1 + p.c2 / p.t2, '', (p, a) => `U = ${p.c1}/${p.t1} + ${p.c2}/${p.t2} = ${a.toFixed(4)}.`, 0.005),
          num('rmbound', { n: [1, 8, 1] }, (p) => `What is the rate-monotonic utilisation bound for ${p.n} task(s)?`, (p) => p.n * (2 ** (1 / p.n) - 1), '', (p, a) => `n(2^(1/n) − 1) = ${a.toFixed(4)}.`, 0.002),
          mcq('inversion', 'Which protocol prevents unbounded priority inversion?', ['Round-robin', 'Priority inheritance', 'FCFS', 'Polling'], 1, 'The lock holder temporarily inherits the waiting task\'s high priority.'),
        ] },
    ],
    viva: [
      ['What is the difference between a microprocessor and a microcontroller?', 'A microcontroller puts the CPU, memory, timers and I/O on one chip for control tasks; a microprocessor needs external memory and peripherals.'],
      ['Why is 11.0592 MHz used with the 8051?', 'It divides exactly to standard baud rates (e.g. 9600 with TH1 = FDh), giving zero baud-rate error.'],
      ['Harvard vs von Neumann architecture?', 'Harvard has separate program and data memories and buses (8051, AVR); von Neumann shares one memory for both.'],
      ['What is a watchdog timer?', 'A timer that resets the MCU unless the program clears it regularly, recovering from hangs.'],
      ['Why does I²C need pull-up resistors?', 'SDA and SCL are open-drain: devices can only pull them low, so resistors pull them high.'],
      ['What is PWM resolution?', 'The number of distinct duty-cycle steps, set by the timer\'s count range (8 bits = 256 steps).'],
      ['What is the difference between hard and soft real-time?', 'Missing a hard deadline is a failure (airbag); missing a soft deadline only lowers quality (video frame).'],
      ['What is debouncing?', 'Ignoring the rapid on/off chatter of a mechanical switch, by a delay or a filter, so one press counts once.'],
    ],
  },
  {
    id: 'signals', title: 'Signals and systems', level: 'Intermediate', color: '#fca5a5',
    lessons: [
      { id: 'sampling', title: 'Sampling and aliasing', minutes: 12, lab: { module: 'communication', label: 'Communication → sampling & PCM' },
        summary: ['A signal must be sampled faster than twice its highest frequency (the Nyquist rate) to be recovered. Anything above fs/2 folds back and appears at a false, lower frequency: aliasing. An anti-aliasing low-pass filter before the ADC removes those components.', 'A tone at f sampled at fs shows up at |f − k·fs| for the k that brings it into 0 … fs/2.'],
        formulas: ['fs > 2·fmax', 'Alias: f_a = |f − round(f/fs)·fs|'],
        questions: [
          num('nyquist', { fmax: [1000, 20000, 500] }, (p) => `A signal contains frequencies up to ${E(p.fmax, 'Hz')}. What is the minimum (Nyquist) sampling rate?`, (p) => 2 * p.fmax, 'Hz', (p, a) => `2·fmax = ${E(a, 'Hz')}.`),
          num('alias', { f: [6000, 15000, 500], fs: { choices: [8000, 10000] } }, (p) => `A ${E(p.f, 'Hz')} tone is sampled at ${E(p.fs, 'Hz')}. At what frequency does it appear?`, (p) => Math.abs(p.f - Math.round(p.f / p.fs) * p.fs), 'Hz', (p, a) => `|f − k·fs| = ${E(a, 'Hz')}.`, 0.001),
          mcq('aaf', 'An anti-aliasing filter is placed', ['after the DAC', 'before the ADC', 'inside the CPU', 'after the speaker'], 1, 'It must remove frequencies above fs/2 before sampling.'),
        ] },
      { id: 'fourier', title: 'Fourier series', minutes: 14, lab: { module: 'sigsys', label: 'Signals & Systems → Fourier series' },
        summary: ['Any periodic signal is a sum of sinusoids at multiples of its fundamental frequency. A square wave of amplitude A contains only odd harmonics with amplitudes 4A/(nπ). Adding more harmonics sharpens the edges, but the partial sum always overshoots by about 9 % at a jump — the Gibbs phenomenon.', 'Parseval\'s theorem says the power is the sum of the powers of the harmonics.'],
        formulas: ['f(t) = a0 + Σ (an cos nω0t + bn sin nω0t)', 'Square wave: bn = 4A/(nπ), n odd', 'Power: P = a0² + ½ Σ (an² + bn²)'],
        questions: [
          num('square-harmonic', { a: [1, 10, 1], n: { choices: [1, 3, 5, 7] } }, (p) => `A square wave of amplitude ±${p.a} V. What is the amplitude of harmonic ${p.n}?`, (p) => 4 * p.a / (p.n * Math.PI), 'V', (p, a) => `4A/(nπ) = ${E(a, 'V')}.`),
          mcq('even-harm', 'A square wave with 50 % duty cycle contains', ['only even harmonics', 'only odd harmonics', 'all harmonics', 'no harmonics'], 1, 'Half-wave symmetry cancels the even harmonics.'),
          mcq('gibbs', 'The Gibbs overshoot near a jump is about', ['0 %', '9 %', '50 %', 'it grows forever'], 1, 'It stays near 9 % of the jump however many harmonics are added.'),
        ] },
      { id: 'laplace', title: 'Laplace transform and stability', minutes: 15, lab: { module: 'sigsys', label: 'Signals & Systems → Laplace' },
        summary: ['The Laplace transform turns differential equations into algebra. A system\'s transfer function H(s) = Y(s)/X(s) has poles (roots of the denominator) that decide its behaviour: poles in the left half-plane give decaying responses (stable), poles on the right grow (unstable).', 'Partial fractions split H(s) into simple terms whose inverse transforms are exponentials and sinusoids. The final-value theorem gives the steady state: lim s·F(s) as s → 0.'],
        formulas: ['L{e^(−at)} = 1/(s + a)', 'Stable ⇔ all poles have Re(p) < 0', 'Final value: f(∞) = lim(s→0) s·F(s)'],
        questions: [
          num('fvt', { k: [1, 20, 1], a: [1, 10, 1] }, (p) => `F(s) = ${p.k} / (s(s + ${p.a})). What is f(∞)?`, (p) => p.k / p.a, '', (p, a) => `lim s·F(s) = ${p.k}/${p.a} = ${a.toFixed(4)}.`),
          num('tau-pole', { a: [1, 50, 1] }, (p) => `A first-order system has its pole at s = −${p.a}. What is its time constant?`, (p) => 1 / p.a, 's', (p, a) => `τ = 1/${p.a} = ${E(a, 's')}.`),
          mcq('stable', 'A system with poles at −2 and +1 is', ['stable', 'unstable', 'marginally stable', 'oscillatory and stable'], 1, 'The pole at +1 gives a growing e^t term.'),
        ] },
      { id: 'ztransform', title: 'Z-transform and difference equations', minutes: 14, lab: { module: 'sigsys', label: 'Signals & Systems → Z-transform' },
        summary: ['Digital systems are described by difference equations such as y[n] = x[n] + 0.5·y[n − 1]. The z-transform turns them into H(z) = B(z)/A(z). A causal system is stable when all its poles lie inside the unit circle |z| < 1.', 'The impulse response of a first-order system with pole a is h[n] = aⁿ for n ≥ 0.'],
        formulas: ['Z{aⁿu[n]} = 1 / (1 − a·z⁻¹)', 'Stable ⇔ |poles| < 1', 'Delay by one sample = multiply by z⁻¹'],
        questions: [
          num('hn', { a: { choices: [0.5, 0.8, -0.5, 0.9] }, n: [2, 6, 1] }, (p) => `y[n] = x[n] + ${p.a}·y[n − 1]. What is h[${p.n}] (impulse response)?`, (p) => p.a ** p.n, '', (p, a) => `h[n] = aⁿ = ${p.a}^${p.n} = ${a.toFixed(5)}.`, 0.001),
          mcq('unit-circle', 'A causal digital filter with a pole at z = 1.2 is', ['stable', 'unstable', 'FIR', 'linear phase'], 1, 'The pole is outside the unit circle, so h[n] grows as 1.2ⁿ.'),
          mcq('fir-stable', 'An FIR filter is always', ['unstable', 'stable', 'recursive', 'minimum phase'], 1, 'All its poles are at z = 0 and its impulse response has finite length.'),
        ] },
      { id: 'dft', title: 'DFT and FFT', minutes: 14, lab: { module: 'sigsys', label: 'Signals & Systems → DFT step by step' },
        summary: ['The DFT turns N time samples into N frequency bins spaced fs/N apart. Bin k corresponds to frequency k·fs/N. A direct DFT needs N² complex multiplications; the radix-2 FFT splits the problem in halves and needs only (N/2)·log2 N.', 'A tone that does not fall exactly on a bin spreads into neighbouring bins (leakage); a window such as Hann reduces it.'],
        formulas: ['X[k] = Σ x[n]·e^(−j2πkn/N)', 'Bin spacing Δf = fs / N', 'FFT multiplications ≈ (N/2)·log2 N'],
        questions: [
          num('binspacing', { fs: { choices: [8000, 44100, 48000, 1000] }, n: { choices: [256, 512, 1024, 4096] } }, (p) => `fs = ${E(p.fs, 'Hz')}, N = ${p.n}. What is the frequency resolution?`, (p) => p.fs / p.n, 'Hz', (p, a) => `fs/N = ${E(a, 'Hz')}.`),
          num('fftmul', { n: { choices: [8, 16, 64, 256, 1024] } }, (p) => `How many complex multiplications does a radix-2 FFT of ${p.n} points need ((N/2)·log2 N)?`, (p) => p.n / 2 * Math.log2(p.n), '', (p, a) => `${p.n}/2 × ${Math.log2(p.n)} = ${a} (direct DFT: ${p.n ** 2}).`, 0),
          mcq('leakage', 'Spectral leakage is reduced by', ['zero padding only', 'applying a window', 'a higher sample rate only', 'rounding'], 1, 'Windows taper the ends of the record so the periodic extension has no jump.'),
        ] },
      { id: 'filters', title: 'Digital filters', minutes: 14, lab: { module: 'dsp', label: 'Signals & DSP → filter designer' },
        summary: ['FIR filters use only past inputs, are always stable and can have exactly linear phase (constant delay). IIR filters reuse past outputs, so they reach a sharp cut-off with far fewer coefficients, but the phase is not linear and they must be checked for stability.', 'A Butterworth filter is maximally flat in the passband; a Chebyshev filter allows ripple to get a steeper roll-off. The bilinear transform maps an analogue design to digital with pre-warped frequencies.'],
        formulas: ['FIR: y[n] = Σ b_k·x[n − k]', 'IIR: y[n] = Σ b_k·x[n − k] − Σ a_k·y[n − k]', 'Butterworth roll-off: 20·N dB/decade', 'Linear-phase FIR delay = (N − 1)/2 samples'],
        questions: [
          num('delay', { n: [11, 201, 2], fs: { choices: [8000, 48000] } }, (p) => `A linear-phase FIR filter has ${p.n} taps at fs = ${E(p.fs, 'Hz')}. What is its delay in seconds?`, (p) => (p.n - 1) / 2 / p.fs, 's', (p, a) => `(N − 1)/2 = ${(p.n - 1) / 2} samples = ${E(a, 's')}.`),
          num('rolloff', { order: [1, 8, 1] }, (p) => `How steep is the stop-band roll-off of an order-${p.order} Butterworth low-pass, in dB/decade?`, (p) => 20 * p.order, 'dB', (p, a) => `20·N = ${a} dB/decade.`, 0),
          mcq('linear-phase', 'Which filter type can have exactly linear phase?', ['IIR Butterworth', 'FIR with symmetric coefficients', 'Chebyshev', 'Elliptic'], 1, 'Symmetric FIR coefficients give a constant group delay.'),
        ] },
    ],
    viva: [
      ['What is the sampling theorem?', 'A band-limited signal with highest frequency fmax can be recovered exactly from samples taken faster than 2·fmax.'],
      ['What is an LTI system?', 'A linear time-invariant system: superposition holds and a delayed input gives an equally delayed output. It is fully described by its impulse response.'],
      ['What is convolution?', 'The output of an LTI system: y[n] = Σ x[k]·h[n − k] — each input sample launches a scaled, shifted copy of the impulse response.'],
      ['ROC of a causal sequence?', 'The outside of a circle: |z| > the largest pole magnitude.'],
      ['Why is the FFT faster than the DFT?', 'It reuses the symmetry and periodicity of the twiddle factors to split an N-point DFT into two N/2-point DFTs repeatedly: O(N log N) instead of O(N²).'],
      ['FIR vs IIR?', 'FIR: finite impulse response, always stable, linear phase possible, more taps. IIR: feedback, fewer coefficients for a sharp cut-off, non-linear phase, stability must be checked.'],
      ['What is the Gibbs phenomenon?', 'The ≈ 9 % overshoot of a truncated Fourier series near a discontinuity, which does not vanish as more terms are added.'],
      ['What is the relation between Laplace and Fourier transforms?', 'The Fourier transform is the Laplace transform evaluated on the jω axis (s = jω), when that axis is in the region of convergence.'],
    ],
  },
  {
    id: 'comm', title: 'Digital communication', level: 'Advanced', color: '#22d3ee',
    lessons: [
      { id: 'am-fm', title: 'AM and FM', minutes: 14, lab: { module: 'communication', label: 'Communication → analog modulation' },
        summary: ['In AM the carrier amplitude follows the message: s(t) = Ac[1 + m·cos ωmt]cos ωct. The spectrum has the carrier and two sidebands at fc ± fm, so the bandwidth is 2fm. Total power is Pc(1 + m²/2), so at best one third of the power carries information.', 'In FM the frequency follows the message. Carson\'s rule estimates the bandwidth as 2(Δf + fm). FM trades bandwidth for noise immunity.'],
        formulas: ['AM bandwidth = 2·fm', 'Pt = Pc·(1 + m²/2)', 'β = Δf / fm', 'Carson: B ≈ 2(Δf + fm)'],
        questions: [
          num('ampower', { pc: [100, 1000, 50], m: { choices: [0.3, 0.5, 0.8, 1] } }, (p) => `An AM transmitter has carrier power ${p.pc} W and modulation index ${p.m}. Find the total power.`, (p) => p.pc * (1 + p.m ** 2 / 2), 'W', (p, a) => `Pc(1 + m²/2) = ${E(a, 'W')}.`),
          num('carson', { df: [5000, 75000, 5000], fm: [1000, 15000, 1000] }, (p) => `FM with peak deviation ${E(p.df, 'Hz')} and message ${E(p.fm, 'Hz')}. Carson bandwidth?`, (p) => 2 * (p.df + p.fm), 'Hz', (p, a) => `2(Δf + fm) = ${E(a, 'Hz')}.`),
          mcq('overmod', 'What happens when the AM index m exceeds 1?', ['Bandwidth halves', 'Envelope distortion (overmodulation)', 'Carrier disappears', 'Nothing'], 1, 'The envelope crosses zero and an envelope detector can no longer follow the message.'),
        ] },
      { id: 'pcm', title: 'PCM and line codes', minutes: 12, lab: { module: 'communication', label: 'Communication → sampling, PCM & line codes' },
        summary: ['Pulse-code modulation samples the signal, quantises each sample to one of 2ⁿ levels and sends n bits. The bit rate is n·fs. Each extra bit improves the signal-to-quantisation-noise ratio by about 6 dB.', 'Line codes shape the bits for the cable: NRZ is simple but has DC and no clock; Manchester puts a transition in every bit (self-clocking, double bandwidth); AMI alternates the polarity of 1s so the average is zero.'],
        formulas: ['Bit rate = n·fs', 'SQNR ≈ 6.02n + 1.76 dB', 'Telephone PCM: 8 bits × 8 kHz = 64 kb/s'],
        questions: [
          num('bitrate', { n: [4, 16, 1], fs: { choices: [8000, 16000, 44100, 48000] } }, (p) => `PCM with ${p.n} bits per sample at ${E(p.fs, 'Hz')}. Bit rate?`, (p) => p.n * p.fs, 'b/s', (p, a) => `n·fs = ${E(a, 'b/s')}.`),
          num('levels', { n: [3, 12, 1] }, (p) => `How many quantisation levels does a ${p.n}-bit PCM system have?`, (p) => 2 ** p.n, '', (p, a) => `2^${p.n} = ${a}.`, 0),
          mcq('manchester', 'Why is Manchester coding used in classic Ethernet?', ['Lowest bandwidth', 'A transition in every bit carries the clock and removes DC', 'It is encrypted', 'It needs no receiver'], 1, 'Self-clocking and DC-free, at the cost of twice the bandwidth.'),
        ] },
      { id: 'modulation-ber', title: 'Digital modulation and BER', minutes: 15, lab: { module: 'communication', label: 'Communication → digital modulation & BER' },
        summary: ['BPSK sends one bit per symbol as ±1; QPSK sends two bits per symbol on two orthogonal carriers with the same bit error rate as BPSK. In AWGN both have BER = Q(√(2Eb/N0)) — about 10⁻⁵ needs Eb/N0 ≈ 9.6 dB.', 'Higher orders such as 16-QAM carry more bits per symbol in the same bandwidth but need more Eb/N0 for the same error rate.'],
        formulas: ['BER(BPSK, QPSK) = Q(√(2·Eb/N0))', 'Bits per symbol = log2 M', 'Symbol rate = bit rate / log2 M'],
        questions: [
          num('symrate', { rb: { choices: [9600, 64000, 1e6, 10e6] }, m: { choices: [2, 4, 8, 16, 64] } }, (p) => `${E(p.rb, 'b/s')} is sent with ${p.m}-ary modulation. What is the symbol rate?`, (p) => p.rb / Math.log2(p.m), 'Bd', (p, a) => `Rb/log2 M = ${E(a, 'Bd')}.`),
          mcq('qpsk-ber', 'For the same Eb/N0, QPSK compared with BPSK has', ['twice the BER', 'the same BER, half the bandwidth', 'lower BER and more bandwidth', 'no relation'], 1, 'Each quadrature arm is an independent BPSK channel.'),
          mcq('qam', '16-QAM carries how many bits per symbol?', ['2', '4', '8', '16'], 1, 'log2 16 = 4.'),
        ] },
      { id: 'coding', title: 'Error-control coding', minutes: 14, lab: { module: 'communication', label: 'Communication → error-control coding' },
        summary: ['A Hamming(7,4) code adds three parity bits to four data bits. Its minimum distance is 3, so it corrects any single-bit error: the syndrome directly gives the position of the wrong bit.', 'CRC detects errors by dividing the message by a generator polynomial and sending the remainder. Convolutional codes with Viterbi decoding are used on noisy radio links.'],
        formulas: ['Hamming: 2^r ≥ m + r + 1', 'Corrects t errors if dmin ≥ 2t + 1', 'Code rate = k/n'],
        questions: [
          num('parity', { m: [4, 120, 1] }, (p) => `How many parity bits r does a Hamming code need for ${p.m} data bits (2^r ≥ m + r + 1)?`, (p) => { let r = 1; while (2 ** r < p.m + r + 1) r += 1; return r; }, '', (p, a) => `Smallest r with 2^r ≥ ${p.m} + r + 1 is ${a}.`, 0),
          num('dmin', { t: [1, 5, 1] }, (p) => `What minimum distance lets a code correct ${p.t} error(s)?`, (p) => 2 * p.t + 1, '', (p, a) => `dmin = 2t + 1 = ${a}.`, 0),
          mcq('crc', 'A CRC is mainly used to', ['correct many errors', 'detect errors', 'encrypt data', 'compress data'], 1, 'The receiver recomputes the remainder; a non-zero result flags an error.'),
        ] },
      { id: 'noise', title: 'Noise and receivers', minutes: 14, lab: { module: 'communication', label: 'Communication → receiver & noise' },
        summary: ['Thermal noise power is kTB: −174 dBm in 1 Hz at room temperature. A receiver\'s noise figure says how much worse it makes the SNR. In a chain of stages, Friis\'s formula shows the first stage matters most: F = F1 + (F2 − 1)/G1 + …', 'A superheterodyne receiver mixes the signal down to a fixed IF; the image frequency fs ± 2·IF must be rejected by the RF filter.'],
        formulas: ['N = k·T·B,  −174 dBm/Hz at 290 K', 'F_total = F1 + (F2 − 1)/G1 + (F3 − 1)/(G1·G2)', 'Image = fs + 2·IF (high-side LO)', 'Sensitivity = −174 + 10 log B + NF + SNR (dBm)'],
        questions: [
          num('noisefloor', { b: { choices: [10e3, 200e3, 1e6, 20e6] }, nf: [2, 10, 1] }, (p) => `Bandwidth ${E(p.b, 'Hz')}, noise figure ${p.nf} dB. What is the noise floor in dBm?`, (p) => -174 + 10 * Math.log10(p.b) + p.nf, 'dBm', (p, a) => `−174 + 10 log B + NF = ${a.toFixed(2)} dBm.`, 0.005),
          num('image', { fs: [550e3, 1600e3, 10e3] }, (p) => `An AM receiver with IF 455 kHz and LO above the signal is tuned to ${E(p.fs, 'Hz')}. What is the image frequency?`, (p) => p.fs + 2 * 455e3, 'Hz', (p, a) => `fs + 2·IF = ${E(a, 'Hz')}.`, 0.001),
          mcq('lna', 'Why is a low-noise amplifier placed first in a receiver?', ['It is cheaper', 'The first stage dominates the overall noise figure', 'To reduce gain', 'To mix the signal'], 1, 'Friis: later stages are divided by the gain before them.'),
        ] },
      { id: 'cellular', title: 'Cellular systems', minutes: 14, lab: { module: 'cellular', label: 'Cellular Planning' },
        summary: ['Cellular networks reuse the same frequencies in cells far enough apart. With cluster size N = i² + ij + j², the co-channel reuse ratio is Q = D/R = √(3N), and with six interferers S/I ≈ Q⁴/6 for a path-loss exponent of 4.', 'Traffic is measured in erlangs (A = calls per hour × holding time / 3600). The Erlang-B formula gives the chance a call is blocked when all channels are busy.'],
        formulas: ['N = i² + ij + j²', 'Q = √(3N)', 'S/I = Qⁿ / 6', 'A = λ·H'],
        questions: [
          num('cluster', { i: [1, 3, 1], j: [0, 3, 1] }, (p) => `What is the cluster size for i = ${p.i}, j = ${p.j}?`, (p) => p.i ** 2 + p.i * p.j + p.j ** 2, '', (p, a) => `N = i² + ij + j² = ${a}.`, 0),
          num('sir', { n: { choices: [3, 4, 7, 9, 12] } }, (p) => `Cluster size ${p.n}, path-loss exponent 4, six interferers. S/I in dB?`, (p) => 10 * Math.log10((3 * p.n) ** 2 / 6), 'dB', (p, a) => `(√(3N))⁴/6 → ${a.toFixed(2)} dB.`, 0.005),
          num('erlang', { users: [100, 1000, 50], calls: [1, 4, 1], minutes: [1, 5, 1] }, (p) => `${p.users} users each make ${p.calls} call(s) per hour lasting ${p.minutes} min. Offered traffic in erlangs?`, (p) => p.users * p.calls * p.minutes / 60, 'E', (p, a) => `A = ${p.users} × ${p.calls} × ${p.minutes}/60 = ${a.toFixed(3)} E.`),
        ] },
    ],
    viva: [
      ['Why is SSB more efficient than DSB-FC AM?', 'It sends one sideband and no carrier, halving the bandwidth and putting all the power into information.'],
      ['What is pre-emphasis in FM?', 'Boosting high audio frequencies before modulation (and cutting them after demodulation) to counter the rising noise at high frequencies in FM.'],
      ['What is ISI and how is it avoided?', 'Inter-symbol interference: symbols spreading into each other. Nyquist pulse shaping (raised cosine) and equalisers avoid it.'],
      ['Define Eb/N0.', 'Energy per bit divided by noise power spectral density — the normalised SNR that lets different schemes be compared.'],
      ['What is the Shannon capacity?', 'C = B·log2(1 + S/N): the maximum error-free bit rate over a channel of bandwidth B and SNR S/N.'],
      ['What is a matched filter?', 'A filter whose impulse response is the time-reversed pulse; it maximises the SNR at the sampling instant.'],
      ['Why is QPSK preferred over BPSK?', 'It carries twice the bits in the same bandwidth with the same BER for a given Eb/N0.'],
      ['What is handoff?', 'Transferring an ongoing call to another cell or channel as the mobile moves; hysteresis prevents ping-pong.'],
    ],
  },
  {
    id: 'rf', title: 'RF and antenna design', level: 'Advanced', color: '#f97316',
    lessons: [
      { id: 'lines', title: 'Transmission lines and reflection', minutes: 14, lab: { module: 'rf', label: 'RF & Antennas → transmission lines' },
        summary: ['At high frequencies a cable is a transmission line with characteristic impedance Z0. A load that is not equal to Z0 reflects part of the wave: Γ = (ZL − Z0)/(ZL + Z0). The standing-wave ratio VSWR = (1 + |Γ|)/(1 − |Γ|) and the return loss −20 log|Γ| measure the mismatch.', 'A quarter-wave line transforms impedance: Zin = Z0²/ZL, so a λ/4 section of √(Z1·Z2) matches Z1 to Z2.'],
        formulas: ['Γ = (ZL − Z0)/(ZL + Z0)', 'VSWR = (1 + |Γ|)/(1 − |Γ|)', 'RL = −20 log10 |Γ|', 'λ/4 transformer: Zt = √(Z0·ZL)'],
        questions: [
          num('gamma', { zl: [10, 300, 5] }, (p) => `A ${p.zl} Ω load on a 50 Ω line. What is |Γ|?`, (p) => Math.abs((p.zl - 50) / (p.zl + 50)), '', (p, a) => `|(${p.zl} − 50)/(${p.zl} + 50)| = ${a.toFixed(4)}.`, 0.01),
          num('vswr', { zl: [10, 300, 5] }, (p) => `A ${p.zl} Ω resistive load on a 50 Ω line. What is the VSWR?`, (p) => Math.max(p.zl, 50) / Math.min(p.zl, 50), '', (p, a) => `For a resistive load VSWR = max(ZL, Z0)/min(ZL, Z0) = ${a.toFixed(3)}.`, 0.01),
          num('qwt', { zl: [20, 200, 5] }, (p) => `What characteristic impedance must a quarter-wave transformer have to match ${p.zl} Ω to 50 Ω?`, (p) => Math.sqrt(50 * p.zl), 'Ω', (p, a) => `√(50 × ${p.zl}) = ${a.toFixed(2)} Ω.`),
        ] },
      { id: 'smith', title: 'Smith chart and matching', minutes: 14, lab: { module: 'rf', label: 'RF & Antennas → Smith chart' },
        summary: ['The Smith chart plots Γ in the complex plane with circles of constant resistance and arcs of constant reactance. Moving along a lossless line rotates the point around the centre; the centre (Γ = 0) is a perfect match.', 'An L-network of one series and one shunt reactance can match any load at one frequency. Single-stub matching uses a line length plus a short- or open-circuited stub.'],
        formulas: ['z = Z/Z0 (normalised)', 'Moving λ/2 along a line = one full turn', 'Series L or C moves along constant-resistance circles'],
        questions: [
          mcq('centre', 'The centre of the Smith chart represents', ['a short circuit', 'an open circuit', 'a matched load (Z = Z0)', 'infinite reactance'], 2, 'Γ = 0 at the centre.'),
          mcq('half-wave', 'A half-wavelength of lossless line', ['inverts the impedance', 'repeats the load impedance', 'shorts the load', 'adds 3 dB loss'], 1, 'λ/2 is a full turn on the chart: Zin = ZL.'),
          num('normalise', { r: [10, 200, 5], x: [-100, 100, 5] }, (p) => `A load ${p.r} ${p.x < 0 ? '−' : '+'} j${Math.abs(p.x)} Ω on a 50 Ω system: what is the normalised resistance r?`, (p) => p.r / 50, '', (p, a) => `r = R/Z0 = ${a.toFixed(3)}.`, 0.005),
        ] },
      { id: 'sparams', title: 'S-parameters', minutes: 12, lab: { module: 'em', label: 'EM & Microwave → S-parameter networks' },
        summary: ['At microwave frequencies we measure waves, not voltages. S11 is the reflection at port 1, S21 the transmission from port 1 to port 2. |S21| in dB is the gain (or insertion loss when negative) and −|S11| in dB is the return loss.', 'A lossless network has a unitary S-matrix: |S11|² + |S21|² = 1. A reciprocal one has S12 = S21.'],
        formulas: ['RL = −20 log10 |S11|', 'IL = −20 log10 |S21|', 'Lossless: |S11|² + |S21|² = 1', 'Amplifier stability: K > 1 and |Δ| < 1'],
        questions: [
          num('il', { s21: [0.5, 0.99, 0.01] }, (p) => `|S21| = ${p.s21}. What is the insertion loss in dB?`, (p) => -20 * Math.log10(p.s21), 'dB', (p, a) => `−20 log ${p.s21} = ${a.toFixed(3)} dB.`, 0.01),
          num('lossless', { s11: [0.1, 0.9, 0.05] }, (p) => `A lossless two-port has |S11| = ${p.s11}. What is |S21|?`, (p) => Math.sqrt(1 - p.s11 ** 2), '', (p, a) => `√(1 − ${p.s11}²) = ${a.toFixed(4)}.`, 0.005),
          mcq('reciprocal', 'A passive network made of R, L, C and lines is', ['always unstable', 'reciprocal (S12 = S21)', 'always lossless', 'non-linear'], 1, 'Passive linear networks without ferrites are reciprocal.'),
        ] },
      { id: 'antennas', title: 'Antennas and arrays', minutes: 14, lab: { module: 'rf', label: 'RF & Antennas → antenna arrays' },
        summary: ['A half-wave dipole is about λ/2 long, has a gain of 2.15 dBi and a radiation resistance near 73 Ω. Gain concentrates power in one direction; effective aperture Ae = G·λ²/(4π) tells how much power an antenna collects.', 'An array of N elements spaced d apart can steer its beam by applying a progressive phase. Spacing above λ/2 risks grating lobes when steering.'],
        formulas: ['λ = c/f', 'Dipole length ≈ λ/2', 'Ae = G·λ²/(4π)', 'Far field begins at 2D²/λ'],
        questions: [
          num('dipole', { f: { choices: [100e6, 433e6, 900e6, 2.4e9] } }, (p) => `How long is a half-wave dipole for ${E(p.f, 'Hz')} (free-space λ/2)?`, (p) => 3e8 / p.f / 2, 'm', (p, a) => `λ/2 = c/(2f) = ${E(a, 'm')}.`),
          num('aperture', { g: [2, 30, 1], f: { choices: [1e9, 2.4e9, 5.8e9, 10e9] } }, (p) => `An antenna with gain ${p.g} (linear) at ${E(p.f, 'Hz')}. Effective aperture?`, (p) => p.g * (3e8 / p.f) ** 2 / (4 * Math.PI), 'm²', (p, a) => `Gλ²/(4π) = ${a.toExponential(3)} m².`),
          mcq('grating', 'To avoid grating lobes while steering widely, element spacing should be at most about', ['λ/10', 'λ/2', '2λ', '10λ'], 1, 'With d ≤ λ/2 no second main lobe enters visible space.'),
        ] },
      { id: 'link', title: 'Link budget (Friis)', minutes: 12, lab: { module: 'rf', label: 'RF & Antennas → link budget' },
        summary: ['The received power in free space is Pr = Pt + Gt + Gr − FSPL (in dB), where the free-space path loss is FSPL = 20 log(4πd/λ) = 32.44 + 20 log f(MHz) + 20 log d(km). Doubling the distance costs 6 dB.', 'The link margin is the received power minus the receiver sensitivity; real links keep 10–20 dB for fading.'],
        formulas: ['FSPL(dB) = 32.44 + 20 log f_MHz + 20 log d_km', 'Pr = Pt + Gt + Gr − FSPL − losses', 'Margin = Pr − sensitivity'],
        questions: [
          num('fspl', { f: { choices: [433, 900, 2400, 5800] }, d: [0.1, 20, 0.1] }, (p) => `Free-space path loss at ${p.f} MHz over ${p.d} km?`, (p) => 32.44 + 20 * Math.log10(p.f) + 20 * Math.log10(p.d), 'dB', (p, a) => `32.44 + 20 log ${p.f} + 20 log ${p.d} = ${a.toFixed(2)} dB.`, 0.005),
          num('pr', { pt: [10, 30, 1], g: [0, 15, 1], loss: [80, 130, 1] }, (p) => `Pt = ${p.pt} dBm, both antennas ${p.g} dBi, path loss ${p.loss} dB. Received power in dBm?`, (p) => p.pt + 2 * p.g - p.loss, 'dBm', (p, a) => `${p.pt} + ${p.g} + ${p.g} − ${p.loss} = ${a} dBm.`, 0.001),
          mcq('double', 'Doubling the distance in free space changes the received power by', ['−3 dB', '−6 dB', '−10 dB', '−20 dB'], 1, 'Power falls as 1/d², i.e. 20 log 2 ≈ 6 dB.'),
        ] },
      { id: 'waveguides', title: 'Waveguides', minutes: 12, lab: { module: 'em', label: 'EM & Microwave → waveguides' },
        summary: ['A hollow metal pipe guides waves only above a cut-off frequency. For a rectangular guide of width a the dominant TE10 mode cuts off at fc = c/(2a); single-mode operation lies between fc(TE10) and the next mode (TE20 at c/a when a > 2b).', 'Inside the guide the wavelength is longer than in free space: λg = λ/√(1 − (fc/f)²).'],
        formulas: ['fc(TE10) = c/(2a)', 'fc(mn) = (c/2)·√((m/a)² + (n/b)²)', 'λg = λ / √(1 − (fc/f)²)'],
        questions: [
          num('fc', { a: { choices: [22.86e-3, 15.8e-3, 10.67e-3, 47.55e-3] } }, (p) => `What is the TE10 cut-off of a rectangular guide with a = ${(p.a * 1000).toFixed(2)} mm?`, (p) => 299792458 / (2 * p.a), 'Hz', (p, a) => `c/(2a) = ${E(a, 'Hz')}.`),
          num('lg', { f: { choices: [8e9, 9e9, 10e9, 11e9, 12e9] } }, (p) => `WR-90 (fc = 6.557 GHz) at ${E(p.f, 'Hz')}: what is the guide wavelength?`, (p) => (299792458 / p.f) / Math.sqrt(1 - (6.557e9 / p.f) ** 2), 'm', (p, a) => `λg = λ/√(1 − (fc/f)²) = ${E(a, 'm')}.`),
          mcq('tem', 'Why can a hollow rectangular waveguide not carry a TEM wave?', ['It is too small', 'A single conductor cannot support a TEM field', 'Metal absorbs it', 'It can'], 1, 'TEM needs at least two separate conductors (like coax).'),
        ] },
    ],
    viva: [
      ['What is characteristic impedance?', 'The ratio of voltage to current of a single travelling wave on a line, set by its geometry and dielectric: √(L/C) for a lossless line.'],
      ['Why is 50 Ω common?', 'It is a compromise between the coax impedance for minimum loss (~77 Ω) and maximum power handling (~30 Ω).'],
      ['What is VSWR of 1?', 'A perfectly matched load: no reflection, so no standing wave.'],
      ['Define antenna gain and directivity.', 'Directivity is the radiation intensity in the best direction relative to an isotropic antenna; gain also includes the antenna efficiency.'],
      ['What is the dominant mode of a rectangular waveguide?', 'TE10, the mode with the lowest cut-off frequency (c/2a).'],
      ['What is the Friis transmission equation?', 'Pr/Pt = Gt·Gr·(λ/(4πd))² for free-space propagation between matched antennas.'],
      ['What is skin depth?', 'The depth at which current density falls to 1/e of its surface value, δ = 1/√(πfμσ); it shrinks as frequency rises.'],
      ['When is an amplifier unconditionally stable?', 'When Rollett\'s K > 1 and |Δ| < 1, so no passive source or load can make it oscillate.'],
    ],
  },
];

export const lessonIndex = () => TRACKS.flatMap((track) => track.lessons.map((lesson) => ({ track: track.id, trackTitle: track.title, ...lesson })));
export const findLesson = (id) => lessonIndex().find((lesson) => lesson.id === id) ?? null;
