export interface TransformerResult { rating: number; ratio: number; pf0: number; iw: number; imu: number; r0: number; x0: number; rEq: number; xEq: number; zEq: number; ratedHv: number; ratedLv: number; coreLoss: number; copperFull: number; efficiency: (fraction: number, pf: number) => number; regulation: (fraction: number, pf: number, lagging?: boolean) => number; maxEfficiencyLoad: number; maxEfficiency: number; percentImpedance: number }
export declare function transformerTests(options?: { kva?: number; hv?: number; lv?: number; oc?: { v: number; i: number; p: number }; sc?: { v: number; i: number; p: number } }): TransformerResult;
export declare function allDayEfficiency(transformer: TransformerResult, cycle: [number, number, number][]): { output: number; copper: number; core: number; efficiency: number };
export declare function dcShuntMotor(options?: { v?: number; ra?: number; ratedIa?: number; ratedRpm?: number; extraRa?: number; fieldFraction?: number }): { kPhi: number; kPhiRated: number; ratedTorque: number; noLoadRpm: number; speedAt: (torque: number) => number; currentAt: (torque: number) => number; backEmfRated: number; stallTorque: number; startingCurrent: number };
export declare function dcSeriesMotor(options?: { v?: number; ra?: number; rse?: number; ratedIa?: number; ratedRpm?: number }): { k: number; atCurrent: (ia: number) => { torque: number; rpm: number }; atTorque: (torque: number) => { torque: number; rpm: number }; ratedTorque: number; startingTorque: number };
export interface InductionOperating { s: number; rpm: number; current: number; pf: number; pin: number; airGap: number; rotorCopper: number; converted: number; output: number; efficiency: number; inducedTorque: number; loadTorque: number }
export declare function inductionMotor(options?: { vLine?: number; r1?: number; x1?: number; xm?: number; r2?: number; x2?: number; poles?: number; frequency?: number; star?: boolean; rotationalLoss?: number }): { vPhase: number; ns: number; ws: number; vth: number; rth: number; xth: number; torque: (s: number) => number; sMax: number; tMax: number; startingTorque: number; operating: (s: number) => InductionOperating };
export declare function ujtOscillator(options?: { vbb?: number; eta?: number; r?: number; cap?: number; vd?: number; vv?: number; iv?: number; ip?: number }): { vp: number; period: number; frequency: number; rMin: number; rMax: number; oscillates: boolean };
export declare function resistanceFiring(options?: { vm?: number; r?: number; rMin?: number; igt?: number; vgt?: number }): { alpha: number | null; fires: boolean; needed: number; maxAlpha?: number };
export declare function snubber(options?: { vs?: number; l?: number; dvdt?: number; zeta?: number }): { rs: number; cs: number; dischargeCurrent: number; check: number };
export declare function seriesString(options?: { vs?: number; n?: number; vbm?: number; deltaIb?: number; deltaQ?: number }): { r: number; c: number; efficiency: number; derating: number };
export declare function switchingLoss(options?: { device?: 'mosfet' | 'igbt'; v?: number; i?: number; tr?: number; tf?: number; frequency?: number; duty?: number; rdsOn?: number; vceSat?: number }): { switching: number; conduction: number; total: number };
