export declare const C: number;
export declare const BOLTZMANN_DBW: number;
export declare const MU_EARTH: number;
export declare const R_EARTH: number;
export declare const SIDEREAL_DAY: number;
export declare function radarRange(options?: { pt?: number; gainDb?: number; frequency?: number; rcs?: number; bandwidth?: number; noiseFigureDb?: number; snrDb?: number; lossDb?: number; pulses?: number }): { lambda: number; smin: number; sminDbm: number; noisePowerDbm: number; rmax: number; snrAt: (range: number) => number };
export declare function pulseRadar(options?: { prf?: number; pulseWidth?: number; pt?: number }): { pri: number; unambiguousRange: number; rangeResolution: number; duty: number; averagePower: number; minimumRange: number; bandwidth: number };
export declare function doppler(options?: { frequency?: number; velocity?: number; prf?: number; count?: number }): { lambda: number; fd: number; blindSpeeds: number[]; firstBlind: number; cancellerGain: number; maxUnambiguousVelocity: number };
export declare function fmcw(options?: { bandwidth?: number; sweepTime?: number; beat?: number; frequency?: number; dopplerVelocity?: number }): { slope: number; range: number; rangeResolution: number; maxBeatFor: (r: number) => number; dopplerShift: number };
export declare function orbit(options?: { perigeeAltitude?: number; apogeeAltitude?: number | null }): { a: number; e: number; period: number; perigeeSpeed: number; apogeeSpeed: number; geostationaryRadius: number };
export declare function orbitTrace(orbit: { a: number; e: number }, points?: number): [number, number][];
export declare function lookAngles(options?: { latitude?: number; longitude?: number; satelliteLongitude?: number; radius?: number | null }): { azimuth: number; elevation: number; slantRange: number; centralAngle: number; visible: boolean };
export declare function satelliteLink(options?: { eirpDbw?: number; frequency?: number; distance?: number; gtDb?: number; otherLossDb?: number; bandwidth?: number }): { fspl: number; cn0: number; cn: number; received: number };
export declare function combineCn(...values: number[]): number;
export declare function gOverT(options?: { antennaGainDb?: number; antennaNoise?: number; feedLossDb?: number; lnaNoise?: number; lnaGainDb?: number; receiverNoise?: number }): { tsys: number; gtDb: number };
export declare function dipolePattern(lengthWavelengths?: number, points?: number): { angles: number[]; field: number[] };
export declare function directivity(field: number[], angles: number[]): number;
export declare function halfPowerBeamwidth(field: number[], angles: number[]): number | null;
export declare function apertureAntenna(options?: { frequency?: number; diameter?: number; efficiency?: number; hornA?: number; hornB?: number; hornEfficiency?: number }): { lambda: number; dishGain: number; dishGainDb: number; dishBeamwidth: number; hornGain: number; hornGainDb: number; effectiveArea: (gain: number) => number; farField: number };
export declare function friisLink(options?: { ptDbm?: number; gtDb?: number; grDb?: number; frequency?: number; distance?: number }): { fspl: number; prDbm: number };
export declare function reflexKlystron(options?: { v0?: number; frequency?: number; spacing?: number; modes?: number }): { modes: { n: number; cycles: number; repeller: number; possible: boolean; efficiency: number }[] };
export declare function twoCavityKlystron(options?: { v0?: number; v1?: number; frequency?: number; drift?: number; beta?: number }): { u0: number; theta0: number; bunching: number; efficiency: number; maxEfficiencyBunching: number; optimumV1: number };
export declare function magnetron(options?: { v0?: number; b0?: number; cathodeRadius?: number; anodeRadius?: number }): { hullField: number; hullVoltage: number; cyclotron: number; oscillates: boolean; regime: string };
export declare function directionalCoupler(options?: { p1?: number; p2?: number; p3?: number; p4?: number }): { coupling: number; directivity: number; isolation: number; insertionLoss: number };
export declare function vswrMeasurement(options?: { vmax?: number; vmin?: number; guideWavelength?: number; minimumWidth?: number | null }): { vswr: number; gamma: number; returnLoss: number; mismatchLossDb: number; doubleMinimum?: number };
