// Workspace routing: chooses the renderer for the active module. Each workspace lives in
// src/workspaces/<area>/<module>.js and exports render<Module>(state) and bind<Module>Events().
import { renderLogic } from '../workspaces/digital/logic.js';
import { renderPower } from '../workspaces/electrical/power.js';
import { renderAdcLab } from '../workspaces/electrical/adc.js';
import { renderEv, renderSensors } from '../workspaces/electrical/sensors-ev.js';
import { renderMachines } from '../workspaces/electrical/machines.js';
import { renderProduct } from '../workspaces/electrical/product.js';
import { renderMeasurement } from '../workspaces/electrical/measure.js';
import { renderNetworkTheory } from '../workspaces/circuit/theory.js';
import { renderFaultHunt } from '../workspaces/circuit/faulthunt.js';
import { renderRtos, renderVlsi } from '../workspaces/digital/vlsi-rtos.js';
import { renderDigital } from '../workspaces/digital/fpga.js';
import { renderSigsys } from '../workspaces/signals/sigsys.js';
import { renderDsp } from '../workspaces/signals/dsp.js';
import { renderSpeech } from '../workspaces/signals/speech.js';
import { renderDip } from '../workspaces/signals/dip.js';
import { renderBio } from '../workspaces/signals/biomed.js';
import { renderControl } from '../workspaces/control/control.js';
import { renderPlc } from '../workspaces/control/plc.js';
import { renderCommunication } from '../workspaces/communication/communication.js';
import { renderInfo } from '../workspaces/communication/info.js';
import { renderNetwork } from '../workspaces/communication/network.js';
import { renderCellular } from '../workspaces/communication/cellular.js';
import { renderWsn } from '../workspaces/communication/wsn.js';
import { renderSdr } from '../workspaces/communication/sdr.js';
import { renderCrypto } from '../workspaces/communication/crypto.js';
import { renderRf } from '../workspaces/rf/rf.js';
import { renderEm } from '../workspaces/rf/em.js';
import { renderRadar } from '../workspaces/rf/radar.js';
import { renderTwin } from '../workspaces/embedded/twin.js';
import { renderPcb } from '../workspaces/pcb/pcb.js';
import { renderCalculators } from '../workspaces/tools/calculators.js';
import { renderNn } from '../workspaces/learning/neural.js';
import { renderConsole } from '../workspaces/learning/console.js';
import { renderLearningHub } from '../workspaces/learning/learning-hub.js';
import { isDcResult } from '../shared/simulation.js';
import { renderMcu } from '../workspaces/embedded/mcu.js';
import { renderBench } from '../workspaces/circuit/bench.js';
import { renderRecords } from '../workspaces/records/records.js';
import { renderCircuit } from '../workspaces/circuit/circuit.js';
import { renderAnalog } from '../workspaces/circuit/analog.js';
import { renderEmbedded } from '../workspaces/embedded/embedded.js';
import { renderToolchains } from '../workspaces/toolchains/toolchains.js';
import { renderEngineeringModule, renderHome } from './home.js';

export function renderWorkspace(state, active) {
  if (state.activeModule === 'toolchains') return renderToolchains(state);
  if (active.id === 'home') return renderHome(state);
  if (active.id === 'circuit') {
    const circuitCompatible = isDcResult(state.simulation) || ['ngspice', 'ngspice-error', 'circuit-transient', 'circuit-ac'].includes(state.simulation?.kind);
    const circuitState = circuitCompatible ? state : { ...state, simulation: null };
    return renderCircuit(circuitState);
  }
  if (active.id === 'dsp') return renderDsp(state);
  if (active.id === 'communication') return renderCommunication(state);
  if (active.id === 'rf') return renderRf(state);
  if (active.id === 'calc') return renderCalculators(state);
  if (active.id === 'pcb') return renderPcb(state);
  if (active.id === 'mcu') return renderMcu(state);
  if (active.id === 'bench') return renderBench(state);
  if (active.id === 'record') return renderRecords(state);
  if (active.id === 'power') return renderPower(state);
  if (active.id === 'adc') return renderAdcLab(state);
  if (active.id === 'sensors') return renderSensors(state);
  if (active.id === 'ev') return renderEv(state);
  if (active.id === 'vlsi') return renderVlsi(state);
  if (active.id === 'rtos') return renderRtos(state);
  if (active.id === 'theory') return renderNetworkTheory(state);
  if (active.id === 'sigsys') return renderSigsys(state);
  if (active.id === 'em') return renderEm(state);
  if (active.id === 'twin') return renderTwin(state);
  if (active.id === 'faulthunt') return renderFaultHunt(state);
  if (active.id === 'machines') return renderMachines(state);
  if (active.id === 'product') return renderProduct(state);
  if (active.id === 'plc') return renderPlc(state);
  if (active.id === 'speech') return renderSpeech(state);
  if (active.id === 'radar') return renderRadar(state);
  if (active.id === 'measure') return renderMeasurement(state);
  if (active.id === 'analog') return renderAnalog(state);
  if (active.id === 'info') return renderInfo(state);
  if (active.id === 'cellular') return renderCellular(state);
  if (active.id === 'crypto') return renderCrypto(state);
  if (active.id === 'wsn') return renderWsn(state);
  if (active.id === 'sdr') return renderSdr(state);
  if (active.id === 'dip') return renderDip(state);
  if (active.id === 'biomed') return renderBio(state);
  if (active.id === 'neural') return renderNn(state);
  if (active.id === 'console') return renderConsole(state);
  if (active.id === 'iot') return renderControl(state);
  if (active.id === 'network') return renderNetwork(state);
  if (active.id === 'fpga') return renderDigital(state);
  if (active.id === 'logic') return renderLogic(state);
  if (active.id === 'embedded') return renderEmbedded(state);
  if (active.id === 'learn') return renderLearningHub(state);
  return renderEngineeringModule(active);
}
