// Shell event wiring, run after every render: top bar (theme, import/export, desktop open/save),
// navigation, home actions, then each workspace's binder. Workspace binders do nothing when their
// elements are not on the page.
import { evaluateLesson } from '../../packages/learning/src/index.mjs';
import { getLesson } from '../../packages/learning/src/catalog.mjs';
import { createProject } from '../core/project.js';
import { getState, notify, recordLearningAttempt, replaceProject, setState, updateProject } from '../core/store.js';
import { bindLogicEvents } from '../workspaces/digital/logic.js';
import { bindPowerEvents } from '../workspaces/electrical/power.js';
import { bindAdcEvents } from '../workspaces/electrical/adc.js';
import { bindSensorEvents } from '../workspaces/electrical/sensors-ev.js';
import { bindMachinesEvents } from '../workspaces/electrical/machines.js';
import { bindProductEvents } from '../workspaces/electrical/product.js';
import { bindMeasurementEvents } from '../workspaces/electrical/measure.js';
import { bindNetworkTheoryEvents } from '../workspaces/circuit/theory.js';
import { bindFaultHuntEvents } from '../workspaces/circuit/faulthunt.js';
import { bindVlsiEvents } from '../workspaces/digital/vlsi-rtos.js';
import { bindSigsysEvents } from '../workspaces/signals/sigsys.js';
import { bindDspEvents } from '../workspaces/signals/dsp.js';
import { bindSpeechEvents } from '../workspaces/signals/speech.js';
import { bindDipEvents } from '../workspaces/signals/dip.js';
import { bindBioEvents } from '../workspaces/signals/biomed.js';
import { bindControlEvents } from '../workspaces/control/control.js';
import { bindPlcEvents } from '../workspaces/control/plc.js';
import { bindCommunicationEvents, bindReceiverEvents } from '../workspaces/communication/communication.js';
import { bindInfoEvents } from '../workspaces/communication/info.js';
import { bindNetprotoEvents, bindNetworkEvents } from '../workspaces/communication/network.js';
import { bindCellularEvents } from '../workspaces/communication/cellular.js';
import { bindWsnEvents } from '../workspaces/communication/wsn.js';
import { bindSdrEvents } from '../workspaces/communication/sdr.js';
import { bindCryptoEvents } from '../workspaces/communication/crypto.js';
import { bindRfEvents } from '../workspaces/rf/rf.js';
import { bindEmEvents } from '../workspaces/rf/em.js';
import { bindRadarEvents } from '../workspaces/rf/radar.js';
import { bindTwinEvents } from '../workspaces/embedded/twin.js';
import { bindPcbEvents } from '../workspaces/pcb/pcb.js';
import { bindCalculatorEvents } from '../workspaces/tools/calculators.js';
import { bindNnEvents } from '../workspaces/learning/neural.js';
import { bindConsoleEvents } from '../workspaces/learning/console.js';
import { bindLearningHubEvents } from '../workspaces/learning/learning-hub.js';
import { circuitEditor } from '../state/circuit-editor.js';
import { EXPERIMENT_MODULES } from '../shared/experiments.js';
import { bindMcuEvents } from '../workspaces/embedded/mcu.js';
import { bindBenchEvents } from '../workspaces/circuit/bench.js';
import { bindRecordEvents } from '../workspaces/records/records.js';
import { bindCircuitEvents } from '../workspaces/circuit/circuit.js';
import { bindAnalogEvents } from '../workspaces/circuit/analog.js';
import { bindEmbeddedEvents } from '../workspaces/embedded/embedded.js';
import { bindDigitalEvents } from '../workspaces/digital/hdl-toolchain.js';
import { cancelDesktopJob, closeNativeSessionForBrowserProject, openDesktopProject, refreshDesktopJobs, reviewArtifactGrant, reviewProcessGrant, revokeArtifactGrant, revokeProcessGrant, saveDesktopProject } from '../services/desktop-project.js';
import { refreshEngineDetection } from '../workspaces/toolchains/toolchains.js';
import { bindAssistantEvents } from './assistant.js';
import { exportProject, saveBrowserProject } from '../services/project-io.js';
import { showCommandPalette, showEngineInfo, showHelp } from './command-palette.js';

export const importInput = document.querySelector('#project-import');

export function bindEvents() {
  document.querySelectorAll('[data-module]').forEach((button) => button.addEventListener('click', () => { circuitEditor.wireSource = null; circuitEditor.selectedWire = null; setState({ activeModule: button.dataset.module, selectedComponentId: null }); }));
  document.querySelector('[data-action="home"]')?.addEventListener('click', () => setState({ activeModule: 'home' }));
  document.querySelector('[data-field="project-name"]')?.addEventListener('change', (event) => updateProject((project) => { project.name = event.target.value.trim() || 'Untitled ENTC project'; }));
  document.querySelector('[data-action="theme"]')?.addEventListener('click', () => updateProject((project) => { project.settings.theme = project.settings.theme === 'dark' ? 'light' : 'dark'; }));
  document.querySelector('[data-action="export"]')?.addEventListener('click', exportProject);
  document.querySelector('[data-action="import"]')?.addEventListener('click', () => importInput.click());
  document.querySelector('[data-action="save-local"]')?.addEventListener('click', saveBrowserProject);
  document.querySelector('[data-action="desktop-open"]')?.addEventListener('click', openDesktopProject);
  document.querySelector('[data-action="desktop-save"]')?.addEventListener('click', saveDesktopProject);
  document.querySelector('[data-action="new-project"]')?.addEventListener('click', async () => { if (await closeNativeSessionForBrowserProject()) { replaceProject(createProject('Untitled ENTC project')); notify('New project created', 'success'); } });
  document.querySelector('[data-action="load-demo"]')?.addEventListener('click', async () => { if (await closeNativeSessionForBrowserProject()) { replaceProject(createProject('Voltage divider demonstration')); setState({ activeModule: 'circuit' }); notify('Demo loaded', 'success'); } });
  document.querySelector('[data-action="help"]')?.addEventListener('click', showHelp);
  document.querySelector('[data-action="skip-to-main"]')?.addEventListener('click', () => document.querySelector('#main-content')?.focus());
  document.querySelector('[data-action="command"]')?.addEventListener('click', showCommandPalette);
  document.querySelector('[data-action="engine-info"]')?.addEventListener('click', showEngineInfo);
  const experimentModules = EXPERIMENT_MODULES;
  document.querySelectorAll('.experiment-list .engine-row').forEach((row) => {
    const id = row.querySelector('b')?.textContent?.trim();
    const module = experimentModules[id];
    if (!module) return;
    row.tabIndex = 0;
    row.setAttribute('role', 'link');
    row.setAttribute('aria-label', `Open ${id} experiment`);
    const open = () => setState({ activeModule: module });
    row.addEventListener('click', open);
    row.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } });
  });
  document.querySelector('[data-action="open-toolchains"]')?.addEventListener('click', () => setState({ activeModule: 'toolchains' }));
  document.querySelector('[data-action="refresh-detection"]')?.addEventListener('click', refreshEngineDetection);
  document.querySelector('[data-action="refresh-jobs"]')?.addEventListener('click', refreshDesktopJobs);
  document.querySelectorAll('[data-action="cancel-job"]').forEach((button) => button.addEventListener('click', () => cancelDesktopJob(button.dataset.jobId)));
  document.querySelector('[data-action="grant-process"]')?.addEventListener('click', reviewProcessGrant);
  document.querySelector('[data-action="grant-artifact"]')?.addEventListener('click', reviewArtifactGrant);
  document.querySelector('[data-action="revoke-process"]')?.addEventListener('click', revokeProcessGrant);
  document.querySelector('[data-action="revoke-artifact"]')?.addEventListener('click', revokeArtifactGrant);
  document.querySelector('[data-action="open-lesson-circuit"]')?.addEventListener('click', () => setState({ activeModule: 'circuit' }));
  document.querySelector('[data-action="check-lesson"]')?.addEventListener('click', () => {
    const simulation = getState().simulation;
    if (!simulation?.nodes || !Number.isFinite(simulation.nodes.out)) { notify('Run the voltage-divider DC analysis first.', 'error'); return; }
    const lesson = getLesson('voltage-divider');
    const evaluation = evaluateLesson(lesson, { output: { kind: 'scalar', data: simulation.nodes.out } });
    recordLearningAttempt('voltage-divider', evaluation.passed);
    setState({ lessonEvaluation: evaluation });
    notify(evaluation.passed ? 'Checkpoint passed' : 'Checkpoint not yet passed', evaluation.passed ? 'success' : 'error');
  });
  document.querySelector('[data-action="check-dsp-lesson"]')?.addEventListener('click', () => {
    const simulation = getState().simulation;
    const lesson = getLesson('dsp-window');
    const evaluation = evaluateLesson(lesson, { samples: simulation?.kind === 'dsp' ? { kind: 'scalar', data: simulation.signal.data.length } : null });
    recordLearningAttempt('dsp-window', evaluation.passed); notify(evaluation.passed ? 'DSP checkpoint passed' : 'Run the Signals experiment first.', evaluation.passed ? 'success' : 'error');
  });
  document.querySelector('[data-action="check-comm-lesson"]')?.addEventListener('click', () => {
    const simulation = getState().simulation;
    const lesson = getLesson('qpsk-ber');
    const evaluation = evaluateLesson(lesson, { ber: simulation?.kind === 'communication' ? { kind: 'report', data: { kind: 'ber', rate: simulation.ber.rate } } : null });
    recordLearningAttempt('qpsk-ber', evaluation.passed); notify(evaluation.passed ? 'BER checkpoint passed' : 'Run the Link Lab experiment first.', evaluation.passed ? 'success' : 'error');
  });
  bindCircuitEvents();
  bindDspEvents();
  bindCommunicationEvents();
  bindRfEvents();
  bindCalculatorEvents();
  bindPcbEvents();
  bindMcuEvents();
  bindBenchEvents();
  bindRecordEvents();
  bindPowerEvents();
  bindAdcEvents();
  bindSensorEvents();
  bindVlsiEvents();
  bindNetworkTheoryEvents();
  bindSigsysEvents();
  bindEmEvents();
  bindTwinEvents();
  bindFaultHuntEvents();
  bindMachinesEvents();
  bindProductEvents();
  bindPlcEvents();
  bindSpeechEvents();
  bindRadarEvents();
  bindMeasurementEvents();
  bindAnalogEvents();
  bindInfoEvents();
  bindReceiverEvents();
  bindCellularEvents();
  bindNetprotoEvents();
  bindCryptoEvents();
  bindWsnEvents();
  bindSdrEvents();
  bindDipEvents();
  bindBioEvents();
  bindNnEvents();
  bindConsoleEvents();
  bindLearningHubEvents();
  bindAssistantEvents();
  bindControlEvents();
  bindNetworkEvents();
  bindDigitalEvents();
  bindLogicEvents();
  bindEmbeddedEvents();
}
