export type DesktopProjectSummary = { name: string; version: number; root: string; project_id: string };
export type DesktopEngineProbe = { id: string; candidates: string[] };
export type DesktopJobRequest = { project_id: string; id: string; operation: string; adapter: string };
export type DesktopJobRecord = { project_id: string; id: string; operation: string; adapter: string; state: string; error: string | null; engine_version: string | null; inputs: string[]; outputs: string[]; arguments: string[]; resource_policy: { timeout_ms: number | null; max_output_bytes: number | null }; diagnostics: string[]; logs: string[]; artifacts: DesktopArtifactReference[]; reproducibility: { inputs: string[]; arguments: string[] }; created_at_ms: number; updated_at_ms: number };
export type DesktopProcessRequest = { executable: string; args?: string[]; cwd?: string; timeout_ms?: number; max_output_bytes?: number };
export type DesktopProcessResult = { ok: boolean; code: number | null; stdout: string; stderr: string; error: string | null };
export type DesktopArtifactReference = { path: string; sha256: string; size: number; mediaType: string };
export type DesktopSerialPollResult = { bytes: number[]; dropped_bytes: number; open: boolean; error: string | null };
export type DesktopDevicePermission = 'device-serial' | 'device-usb' | 'device-capture' | 'device-programmer';
export type DesktopBridge = {
  readonly available: boolean;
  pickProjectDirectory(): Promise<string | null>;
  openProject(root: string): Promise<DesktopProjectSummary>;
  detectEngines(probes: DesktopEngineProbe[]): Promise<unknown[]>;
  readOpenProject(): Promise<Record<string, unknown>>;
  saveOpenProject(manifest: Record<string, unknown>): Promise<DesktopProjectSummary>;
  closeProject(): Promise<void>;
  enqueueJob(request: DesktopJobRequest): Promise<DesktopJobRecord>;
  getJob(projectId: string, id: string): Promise<DesktopJobRecord>;
  listJobs(projectId: string): Promise<DesktopJobRecord[]>;
  transitionJob(projectId: string, id: string, next: string, error?: string): Promise<DesktopJobRecord>;
  drainEvents(projectId: string): Promise<Array<Record<string, unknown>>>;
  storeArtifact(projectId: string, path: string, bytes: number[] | Uint8Array, mediaType: string): Promise<DesktopArtifactReference>;
  verifyArtifact(projectId: string, reference: DesktopArtifactReference): Promise<void>;
  registerArtifact(projectId: string, reference: DesktopArtifactReference): Promise<DesktopProjectSummary>;
  registerGeneratedArtifact(projectId: string, path: string, mediaType: string): Promise<DesktopArtifactReference>;
  readArtifact(projectId: string, reference: DesktopArtifactReference, maxBytes?: number): Promise<number[]>;
  grantProcessExecution(projectId: string, acknowledge?: boolean): Promise<void>;
  grantArtifactWrite(projectId: string, acknowledge?: boolean): Promise<void>;
  grantDeviceTarget(projectId: string, permission: DesktopDevicePermission, target: string, acknowledge?: boolean): Promise<void>;
  revokeDeviceTarget(projectId: string, permission: DesktopDevicePermission, target: string): Promise<void>;
  revokeProcessExecution(projectId: string): Promise<void>;
  revokeArtifactWrite(projectId: string): Promise<void>;
  startProcess(projectId: string, id: string, request: DesktopProcessRequest): Promise<void>;
  startDeviceProcess(projectId: string, id: string, permission: DesktopDevicePermission, target: string, request: DesktopProcessRequest): Promise<void>;
  cancelProcess(projectId: string, id: string): Promise<void>;
  pollProcess(projectId: string, id: string): Promise<DesktopProcessResult | null>;
  startSerial(projectId: string, id: string, target: string, baud: number, maxBufferBytes?: number): Promise<void>;
  pollSerial(projectId: string, id: string, maxBytes?: number): Promise<DesktopSerialPollResult>;
  writeSerial(projectId: string, id: string, bytes: number[] | Uint8Array): Promise<void>;
  closeSerial(projectId: string, id: string): Promise<void>;
};
export declare const DESKTOP_UNAVAILABLE_CODE: 'DESKTOP_UNAVAILABLE';
export declare function createDesktopBridge(invoke?: (command: string, args?: Record<string, unknown>) => Promise<unknown>): DesktopBridge;
export declare const desktopBridge: DesktopBridge;
