import { createHash } from 'node:crypto';
import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'dist');
const packageManifest = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));

// The browser build owns the generated preview files but must not silently
// discard native release evidence generated by `npm run native:sbom`.
const nativeEvidenceNames = ['NATIVE-BUILD-SBOM.spdx.json', 'NATIVE-THIRD-PARTY-NOTICES.txt'];
const preservedNativeEvidence = new Map();
for (const name of nativeEvidenceNames) {
  try { preservedNativeEvidence.set(name, await readFile(resolve(output, name))); } catch {}
}

// dist is generated output and is intentionally safe to recreate.
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(resolve(root, 'index.html'), resolve(output, 'index.html'));
await cp(resolve(root, 'src'), resolve(output, 'src'), { recursive: true });
await cp(resolve(root, 'assets'), resolve(output, 'assets'), { recursive: true });
await cp(resolve(root, 'LICENSE'), resolve(output, 'LICENSE'));
await writeFile(resolve(output, 'THIRD-PARTY-NOTICES.txt'), 'OpenENTC Studio browser preview\n\nNo third-party engine binaries or libraries are bundled in this artifact. External toolchains remain user-managed and subject to their own upstream licence terms.\n');
await writeFile(resolve(output, 'BUILD-METADATA.json'), `${JSON.stringify({
  product: 'OpenENTC Studio',
  version: packageManifest.version,
  kind: 'browser-preview-static',
  nativeDesktop: false,
}, null, 2)}\n`);
await writeFile(resolve(output, 'BUILD-SBOM.spdx.json'), `${JSON.stringify({
  spdxVersion: 'SPDX-2.3',
  dataLicense: 'CC0-1.0',
  SPDXID: 'SPDXRef-DOCUMENT',
  name: `OpenENTC-Studio-${packageManifest.version}-browser-preview`,
  documentNamespace: `https://openentc.org/spdx/openentc-studio/${packageManifest.version}/browser-preview`,
  creationInfo: { created: '2026-09-28T00:00:00Z', creators: ['Tool: openentc-studio-build'] },
  packages: [{ SPDXID: 'SPDXRef-Package-OpenENTC-Studio', name: 'OpenENTC Studio', versionInfo: packageManifest.version, downloadLocation: 'NOASSERTION', filesAnalyzed: false, licenseConcluded: 'GPL-3.0-or-later', licenseDeclared: 'GPL-3.0-or-later', copyrightText: 'NOASSERTION' }],
  relationships: [{ spdxElementId: 'SPDXRef-DOCUMENT', relationshipType: 'DESCRIBES', relatedSpdxElement: 'SPDXRef-Package-OpenENTC-Studio' }],
  annotations: [{ annotationDate: '2026-09-28T00:00:00Z', annotationType: 'OTHER', annotator: 'Tool: openentc-studio-build', comment: 'External engineering engines are user-managed and are not bundled in this browser preview.' }],
}, null, 2)}\n`);

async function filesUnder(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0)) {
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    const fullPath = resolve(directory, entry.name);
    if (entry.isDirectory()) files.push(...await filesUnder(fullPath, relativePath));
    else if (entry.isFile()) files.push({ path: relativePath, fullPath });
  }
  return files;
}

const manifest = [];
for (const file of await filesUnder(output)) {
  const bytes = await readFile(file.fullPath);
  const info = await stat(file.fullPath);
  manifest.push({
    path: file.path,
    bytes: info.size,
    sha256: createHash('sha256').update(bytes).digest('hex'),
  });
}
manifest.sort((left, right) => left.path < right.path ? -1 : left.path > right.path ? 1 : 0);
await writeFile(resolve(output, 'BUILD-MANIFEST.json'), `${JSON.stringify({ format: 'openentc-build-manifest', version: 1, files: manifest }, null, 2)}\n`);
await writeFile(resolve(output, 'SHA256SUMS.txt'), `${manifest.map((entry) => `${entry.sha256}  ${entry.path}`).join('\n')}\n`);

for (const [name, bytes] of preservedNativeEvidence) await writeFile(resolve(output, name), bytes);

console.log(`Static browser preview written to ${output}`);
