#!/usr/bin/env node
// Generate docs/feature-status.md from capabilities/ledger.json (state, review, limitations) and
// validation/manifest.json (which engines have reference checks). Do not edit the output by hand;
// tests/governance.test.mjs fails when it is out of date.
//
//   node scripts/feature-status.mjs            write the file
//   node scripts/feature-status.mjs --check    exit 1 if it is out of date
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(root, 'docs', 'feature-status.md');

/** Escape text for a Markdown table cell: backslashes first, then pipes. */
const cell = (text) => String(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|');

const firstSentence = (text) => {
  const match = /^(.+?[.!?])(\s|$)/.exec(String(text).replace(/\s+/g, ' ').trim());
  return cell((match ? match[1] : String(text)).slice(0, 220));
};

export function renderFeatureStatus(ledger, validation) {
  const validated = new Map();
  for (const entry of validation.entries) {
    const key = entry.engine.replace(/\/$/, '');
    validated.set(key, [...(validated.get(key) ?? []), entry.reference]);
  }
  const referencesFor = (capability) => {
    const refs = new Set();
    for (const evidence of capability.evidence) for (const [engine, list] of validated) if (evidence.startsWith(engine)) list.forEach((ref) => refs.add(ref));
    return [...refs].sort();
  };
  const counts = Object.fromEntries(ledger.states.map((state) => [state, ledger.capabilities.filter((c) => c.state === state).length]));
  const reviewed = ledger.capabilities.filter((c) => c.review === 'independently-reviewed').length;
  const rows = ledger.capabilities.map((c) => `| \`${c.id}\` | ${cell(c.surface)} | ${c.state} | ${referencesFor(c).join(', ') || '—'} | ${c.review === 'independently-reviewed' ? 'yes' : 'no'} | ${firstSentence(c.limitations)} |`);
  return `# Feature status (generated)

Generated by \`node scripts/feature-status.mjs\` from [\`capabilities/ledger.json\`](../capabilities/ledger.json)
and [\`validation/manifest.json\`](../validation/manifest.json). Do not edit by hand.

**Product status:** alpha. Results come from educational models. Nothing here is certified,
laboratory-grade or hardware-qualified.

| State | Capabilities |
|---|---|
${ledger.states.map((state) => `| ${state} | ${counts[state]} |`).join('\n')}
| **total** | ${ledger.capabilities.length} |

Independently reviewed: **${reviewed} of ${ledger.capabilities.length}**. Reference checks: ${validation.entries.length} entries in the validation manifest.

State meanings: **built-in** = works inside OpenENTC; **integrated** / **interoperable** = uses an
external tool the user installs; **unavailable** = planned or blocked, with no fake result;
**unsupported** = out of scope.

| Capability | Surface | State | Reference checks | Independent review | Main limitation |
|---|---|---|---|---|---|
${rows.join('\n')}
`;
}

if (process.argv[1] && path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1])) {
  const text = renderFeatureStatus(JSON.parse(readFileSync(path.join(root, 'capabilities/ledger.json'), 'utf8')), JSON.parse(readFileSync(path.join(root, 'validation/manifest.json'), 'utf8')));
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(output, 'utf8'); } catch { /* missing counts as out of date */ }
    if (current !== text) { console.error('docs/feature-status.md is out of date: run node scripts/feature-status.mjs'); process.exitCode = 1; }
  } else {
    writeFileSync(output, text);
    console.log('Wrote docs/feature-status.md');
  }
}
